const fs = require('fs');

const hrJobs = [
  {
    id: 501,
    title: 'Trưởng Phòng Tuyển Dụng Nhân Tài (Talent Acquisition Lead)',
    company: 'FPT Software Global',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng phòng / Quản lý',
    type: 'Hybrid',
    isLightningBadge: true,
    lightningStats: { applied30d: 20, evaluated14d: 19, responseRate: 95, lastReviewed: '12:00' },
    updated: '10 phút trước',
    verified: true,
    skills: ['Tech Recruitment', 'Talent Sourcing', 'Headhunting', 'Employer Branding'],
    jdSummary: [
      'Chịu trách nhiệm hoàn thành chỉ tiêu tuyển dụng 500+ kỹ sư phần mềm cao cấp hàng năm.',
      'Xây dựng quan hệ hợp tác với các trường đại học công nghệ hàng đầu và cộng đồng developer.',
      'Ứng dụng công nghệ AI ATS để tối ưu thời gian tuyển dụng (Time-to-Hire).'
    ],
    perks: ['Thưởng tuyển dụng theo năng suất hàng tháng', 'Gói bảo hiểm FPT Care cho cả gia đình'],
    aiMatch: 95
  },
  {
    id: 502,
    title: 'HR Business Partner (HRBP) - Khối Công Nghệ',
    company: 'VNG Corporation',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '30 - 48 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior / Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '35 phút trước',
    verified: true,
    skills: ['HRBP', 'Quản trị nhân tài', 'Đánh giá KPI / OKRs', 'Văn hóa doanh nghiệp'],
    jdSummary: [
      'Đồng hành chiến lược với Giám đốc khối sản phẩm Game & Zalo về quy hoạch nguồn nhân lực.',
      'Triển khai các chương trình đánh giá hiệu suất, thăng tiến và giữ chân nhân tài công nghệ.',
      'Giải quyết các vấn đề quan hệ lao động và tư vấn phát triển tổ chức (OD).'
    ],
    perks: ['Làm việc tại không gian sáng tạo VNG Campus', 'Thưởng performance theo quý'],
    aiMatch: 93
  },
  {
    id: 503,
    title: 'Chuyên Viên C&B & Chính Sách Nhân Sự Cao Cấp',
    company: 'Tập đoàn Công nghiệp - Viễn thông Quân đội (Viettel)',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 18, evaluated14d: 16, responseRate: 89, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['C&B', 'Luật lao động', 'Xây dựng thang bảng lương 3P', 'Thuế TNCN & BHXH'],
    jdSummary: [
      'Quản lý bảng lương và chế độ đãi ngộ hàng tháng cho hơn 1.000 cán bộ nhân viên.',
      'Khảo sát lương thưởng thị trường (Salary Benchmarking) để đề xuất điều chỉnh bảng lương 3P.',
      'Tối ưu hóa các chính sách phúc lợi và đảm bảo tuân thủ 100% Luật lao động hiện hành.'
    ],
    perks: ['Môi trường quân đội kỷ luật và chuyên nghiệp', 'Phúc lợi toàn diện và ổn định lâu dài'],
    aiMatch: 90
  },
  {
    id: 504,
    title: 'Trưởng Phòng Hành Chính & Quản Trị Vận Hành Văn Phòng',
    company: 'Bitexco Group',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '25 - 38 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Trưởng phòng',
    type: 'Toàn thời gian',
    isLightningBadge: false,
    lightningStats: { applied30d: 14, evaluated14d: 10, responseRate: 71, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Quản trị hành chính', 'Facility Management', 'Quản lý chi phí', 'Đấu thầu nhà cung cấp'],
    jdSummary: [
      'Quản trị toàn bộ công tác vận hành, an ninh và lễ tân tại trụ sở tập đoàn.',
      'Đàm phán hợp đồng mua sắm trang thiết bị văn phòng và quản lý chi phí hành chính định kỳ.',
      'Tổ chức các sự kiện nội bộ, lễ kỷ niệm và hậu cần cho Ban Lãnh Đạo tập đoàn.'
    ],
    perks: ['Làm việc tại tòa tháp Bitexco Financial Tower', 'Chế độ nghỉ phép 15 ngày/năm'],
    aiMatch: 85
  },
  {
    id: 505,
    title: 'Learning & Development (L&D) Specialist',
    company: 'Sun Group Corporation',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '20 - 32 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & Đà Nẵng',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 10, responseRate: 83, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Đào tạo nội bộ', 'Khung năng lực', 'E-Learning', 'Phát triển lãnh đạo'],
    jdSummary: [
      'Khảo sát nhu cầu đào tạo (TNA) của các khối vận hành du lịch và quản lý dự án.',
      'Thiết kế giáo trình và tổ chức các khóa đào tạo nâng cao kỹ năng mềm và kỹ năng chuyên môn.',
      'Vận hành hệ thống học tập trực tuyến LMS cho toàn bộ cán bộ nhân viên tập đoàn.'
    ],
    perks: ['Được tham gia các chương trình đào tạo quốc tế', 'Phúc lợi du lịch nghỉ dưỡng'],
    aiMatch: 88
  },
  {
    id: 506,
    title: 'Chuyên Viên Phát Triển Văn Hóa Doanh Nghiệp & EB',
    company: 'Ngân hàng Techcombank',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 13, responseRate: 87, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Employer Branding', 'Truyền thông nội bộ', 'Tổ chức sự kiện', 'Sáng tạo nội dung'],
    jdSummary: [
      'Lên kế hoạch và triển khai các chiến dịch xây dựng Thương hiệu Nhà tuyển dụng (Employer Branding).',
      'Sản xuất các ấn phẩm truyền thông nội bộ, radio và bản tin định kỳ gắn kết nhân viên.',
      'Chủ trì các hoạt động teambuilding, phong trào thể thao và trách nhiệm xã hội CSR.'
    ],
    perks: ['Môi trường ngân hàng chuyển đổi số xuất sắc nhất', 'Chế độ đãi ngộ và lộ trình nghề nghiệp rõ ràng'],
    aiMatch: 91
  },
  {
    id: 507,
    title: 'HR Operations Specialist (Quản Trị Nhân Sự Khối Vận Hành Kho Vận)',
    company: 'Shopee Vietnam (SPX Express)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '20 - 32 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM & Bắc Ninh',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 17, evaluated14d: 16, responseRate: 94, lastReviewed: '12:00' },
    updated: '25 phút trước',
    verified: true,
    skills: ['HR Operations', 'Quản lý hợp đồng lao động', 'Chấm công ca kíp', 'Thực thi quy chế'],
    jdSummary: [
      'Quản lý hồ sơ nhân sự và ký kết hợp đồng lao động cho hơn 2.000 nhân viên kho vận logistics.',
      'Giám sát dữ liệu chấm công vân tay, giải quyết phép năm và chế độ thai sản, ốm đau kịp thời.',
      'Tổ chức tiếp nhận nhân sự mới (Onboarding) và đào tạo nội quy an toàn lao động.'
    ],
    perks: ['Môi trường E-commerce năng động', 'Phụ cấp ăn ca và xe đưa đón'],
    aiMatch: 89
  },
  {
    id: 508,
    title: 'Giám Đốc Nhân Sự Khối Vận Hành Bán Lẻ (HR Director WinMart)',
    company: 'Masan Group (WinCommerce)',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '45 - 75 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: 'Trên 5 năm',
    level: 'Giám đốc khối',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '40 phút trước',
    verified: true,
    skills: ['HR Strategy', 'Quản trị nhân lực bán lẻ quy mô lớn', 'Quan hệ lao động', 'Tối ưu định biên'],
    jdSummary: [
      'Hoạch định chiến lược nhân sự toàn diện cho hơn 30.000 nhân sự chuỗi siêu thị WinMart và WinMart+.',
      'Thiết kế cơ chế lương thưởng kích thích năng suất lao động tại điểm bán (Productivity-based Pay).',
      'Xây dựng đội ngũ kế thừa và chuẩn hóa tiêu chuẩn dịch vụ khách hàng 5 sao.'
    ],
    perks: ['Gói lương thưởng cạnh tranh top tập đoàn bán lẻ', 'Xe ô tô đưa đón lãnh đạo'],
    aiMatch: 96
  },
  {
    id: 509,
    title: 'Trưởng Nhóm Thu Hút Nhân Tài Cấp Cao (Executive Search Lead)',
    company: 'Tập đoàn Vingroup',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '35 - 55 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Executive Search', 'Headhunting C-Level', 'Tuyển dụng nhân sự quốc tế', 'Đàm phán đãi ngộ'],
    jdSummary: [
      'Tìm kiếm và thu hút các chuyên gia hàng đầu thế giới về trí tuệ nhân tạo, ô tô điện và y tế.',
      'Phỏng vấn đánh giá năng lực lãnh đạo và tư vấn mức đãi ngộ cho Hội đồng Quản trị.',
      'Đảm bảo trải nghiệm ứng viên cao cấp đạt chuẩn quốc tế từ lúc tiếp cận đến khi hòa nhập.'
    ],
    perks: ['Phúc lợi đặc quyền hệ sinh thái Vingroup (Vinhomes, Vinmec, Vinpearl)', 'Thưởng thành tích cao'],
    aiMatch: 95
  },
  {
    id: 510,
    title: 'Quản Lý Đào Tạo & Phát Triển Chuỗi Siêu Thị Toàn Quốc',
    company: 'Công ty Cổ phần Đầu tư Thế Giới Di Động (MWG)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Quản lý đào tạo',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Retail Training', 'Văn hóa Tận Tâm Phục Vụ', 'Đào tạo kỹ năng bán hàng', 'Mobile Learning App'],
    jdSummary: [
      'Quản lý hệ thống đào tạo hội nhập văn hóa phục vụ khách hàng cho hàng nghìn nhân viên mới mỗi tháng.',
      'Sản xuất các video micro-learning đào tạo tính năng sản phẩm công nghệ mới trên app nội bộ.',
      'Đánh giá hiệu quả ứng dụng kiến thức vào thực tế và cải thiện chỉ số hài lòng khách hàng NPS.'
    ],
    perks: ['Gói cổ phiếu thưởng ESOP thường niên', 'Môi trường làm việc thân thiện đoàn kết'],
    aiMatch: 92
  },
  {
    id: 511,
    title: 'Chuyên Viên Quan Hệ Lao Động & Tuân Thủ (ER Specialist)',
    company: 'Samsung Display Vietnam (SDV)',
    logo: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '22 - 36 triệu',
    salaryIsOrange: false,
    location: 'Bắc Ninh & Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Employee Relations', 'Giải quyết tranh chấp lao động', 'Đối thoại công đoàn', 'Pháp lý lao động'],
    jdSummary: [
      'Xử lý các vấn đề quan hệ lao động, kỷ luật lao động và khiếu nại của người lao động đúng luật.',
      'Tổ chức hội nghị người lao động định kỳ và phối hợp với Ban Chấp hành Công đoàn cơ sở.',
      'Đảm bảo nhà máy luôn đạt điểm đánh giá cao trong các cuộc đánh giá trách nhiệm xã hội RBA.'
    ],
    perks: ['Xe đưa đón CBNV khắp các tuyến Hà Nội - Bắc Ninh', 'Bữa ăn miễn phí và chế độ thưởng lớn'],
    aiMatch: 90
  },
  {
    id: 512,
    title: 'HRBP Leader (Khối Viễn Thông & Hạ Tầng Số Doanh Nghiệp)',
    company: 'Tập đoàn Công nghệ CMC (CMC Corporation)',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng nhóm HRBP',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['HRBP IT', 'Quy hoạch tổ chức', 'Đánh giá năng lực nhân sự', 'Giữ chân nhân tài'],
    jdSummary: [
      'Đối tác nhân sự chiến lược cho các đơn vị thành viên khối hạ tầng số và an ninh mạng CMC.',
      'Xây dựng ma trận kỹ năng chuyên môn và lộ trình thăng tiến nghề nghiệp cho kỹ sư công nghệ.',
      'Tham mưu cơ chế lương thưởng khích lệ tinh thần đổi mới sáng tạo và chuyển đổi số.'
    ],
    perks: ['Môi trường làm việc tôn trọng cá nhân', 'Chế độ phúc lợi tập đoàn công nghệ toàn diện'],
    aiMatch: 91
  },
  {
    id: 513,
    title: 'People Operations Partner (Chính Sách & Trải Nghiệm Nhân Viên)',
    company: 'Grab Vietnam',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'People Partner',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 92, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['People Operations', 'Employee Experience', 'Onboarding tự động hóa', 'Workday HRIS'],
    jdSummary: [
      'Tối ưu hóa các điểm chạm trong hành trình trải nghiệm nhân viên từ gia nhập đến rời tổ chức.',
      'Vận hành hệ thống quản lý thông tin nhân sự toàn cầu Workday mượt mà và chính xác.',
      'Tổ chức các diễn đàn đối thoại mở Grabbers All-Hands và khảo sát mức độ gắn kết Pulse Survey.'
    ],
    perks: ['Môi trường làm việc linh hoạt chuẩn quốc tế', 'Gói phụ cấp GrabCredits hàng tháng'],
    aiMatch: 93
  },
  {
    id: 514,
    title: 'Chuyên Viên Khảo Sát & Xây Dựng Khung Năng Lực (Talent Management)',
    company: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Talent Management', 'Khung năng lực từ điển chức danh', 'Assessment Center', 'Quy hoạch kế thừa'],
    jdSummary: [
      'Xây dựng và chuẩn hóa bộ từ điển năng lực chuyên môn cho từng khối phòng ban trong ngân hàng.',
      'Thiết kế bài kiểm tra đánh giá năng lực định kỳ tại trung tâm khảo thí Assessment Center.',
      'Nhận diện các nhân sự có tiềm năng cao (HiPo) để đưa vào chương trình đào tạo quản trị viên tập sự.'
    ],
    perks: ['Môi trường ngân hàng chuyển đổi số năng động nhất', 'Chế độ đãi ngộ xứng đáng'],
    aiMatch: 89
  },
  {
    id: 515,
    title: 'Trưởng Bộ Phận Tuyển Dụng Quốc Tế (Global Talent Acquisition)',
    company: 'Tập đoàn VinFast Toàn Cầu',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '35 - 60 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng bộ phận',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Global Recruitment', 'Kỹ sư ô tô điện', 'Thị trường Mỹ/Canada/Châu Âu', 'Relocation Package'],
    jdSummary: [
      'Chịu trách nhiệm tuyển dụng nhân sự cấp quản lý và chuyên gia tại các văn phòng VinFast Bắc Mỹ và châu Âu.',
      'Xây dựng chính sách luân chuyển cán bộ quốc tế (Relocation & Expat Policies).',
      'Đại diện tập đoàn tham gia các ngày hội việc làm và triển lãm công nghệ ô tô quốc tế.'
    ],
    perks: ['Ưu đãi mua ô tô điện VinFast đặc quyền', 'Cơ hội công tác nước ngoài thường xuyên'],
    aiMatch: 95
  },
  {
    id: 516,
    title: 'Quản Trị Hành Chính & Cung Ứng Vật Tư Văn Phòng Toàn Quốc',
    company: 'Tập đoàn Golden Gate (Golden Gate Group)',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '20 - 32 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Hành chính văn phòng', 'Đấu thầu mua sắm', 'Quản lý tài sản cố định', 'Facility Services'],
    jdSummary: [
      'Quản lý hợp đồng thuê trụ sở văn phòng, dịch vụ an ninh và vệ sinh tòa nhà.',
      'Thương thảo giá và ký kết hợp đồng cung cấp đồ dùng văn phòng, máy in và dịch vụ IT support.',
      'Kiểm kê tài sản định kỳ và thanh lý thiết bị cũ hỏng theo đúng quy trình kiểm toán.'
    ],
    perks: ['Ưu đãi 30% tại toàn bộ hệ thống nhà hàng Golden Gate', 'Môi trường làm việc thân thiện'],
    aiMatch: 87
  },
  {
    id: 517,
    title: 'Compensation & Benefits Lead (Xây Dựng Cơ Chế Thưởng ESOP)',
    company: 'One Mount Group',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '30 - 50 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng nhóm C&B',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Total Rewards', 'ESOP Structure', 'Thang bảng lương công nghệ', 'Khảo sát Mercer/WTW'],
    jdSummary: [
      'Thiết kế gói đãi ngộ tổng thể (Total Rewards) cạnh tranh nhất ngành công nghệ cho One Mount.',
      'Xây dựng quy chế và quản lý kế hoạch phân phối cổ phiếu thưởng ESOP cho nhân sự chủ chốt.',
      'Phân tích chi phí ngân sách nhân sự (HR Cost) và đề xuất phương án tối ưu hóa hiệu suất chi trả.'
    ],
    perks: ['Gói khám sức khỏe Vinmec VIP', 'Chế độ làm việc linh hoạt Hybrid'],
    aiMatch: 94
  },
  {
    id: 518,
    title: 'Internal Communications & Culture Specialist',
    company: 'Công ty Cổ phần Be Group',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '18 - 28 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'TP.HCM',
    exp: '1-3 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Truyền thông nội bộ', 'Văn hóa startup công nghệ', 'Sản xuất bản tin video', 'Townhall Event'],
    jdSummary: [
      'Chủ trì sản xuất bản tin nội bộ hàng tuần, podcast và video truyền cảm hứng văn hóa Be.',
      'Tổ chức các buổi gặp gỡ toàn thể CBNV (Monthly Townhall) kết nối lãnh đạo và nhân viên.',
      'Lên kế hoạch tổ chức các sự kiện mừng sinh nhật công ty, Ngày hội gia đình và tiệc Year End Party.'
    ],
    perks: ['Gói di chuyển Be miễn phí', 'Môi trường làm việc trẻ trung sáng tạo'],
    aiMatch: 88
  },
  {
    id: 519,
    title: 'Trưởng Nhóm Quản Trị Trải Nghiệm Nhân Viên (EX Specialist)',
    company: 'Ngân hàng TMCP Quân Đội (MB Bank)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['Employee Experience', 'HR Digital Transformation', 'MB WOW Culture', 'Lắng nghe phản hồi'],
    jdSummary: [
      'Xây dựng và số hóa toàn bộ trải nghiệm nhân viên trên ứng dụng MB Nhân Sự Thông Minh.',
      'Khảo sát chỉ số hài lòng nhân viên eNPS và đề xuất các cải tiến về môi trường làm việc số.',
      'Triển khai các chương trình ghi nhận và khen thưởng tức thì (Spot Bonus, Kudos).'
    ],
    perks: ['Phúc lợi ngân hàng thuộc top tốt nhất Việt Nam', 'Thưởng các dịp lễ tết chu đáo'],
    aiMatch: 92
  },
  {
    id: 520,
    title: 'HR Business Partner (Khối Logistics & Supply Chain)',
    company: 'Tiki Corporation (TikiNOW Smart Logistics)',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '24 - 38 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM & Bình Dương',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'HRBP Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['HRBP Logistics', 'Định biên nhân sự kho vận', 'Năng suất lao động ca kíp', 'An toàn lao động'],
    jdSummary: [
      'Làm việc trực tiếp cùng Giám đốc khối kho vận TikiNOW để giải quyết các bài toán nguồn lực mùa cao điểm.',
      'Tối ưu hóa chi phí nhân sự trên mỗi đơn hàng đóng gói và giao nhận hoàn tất.',
      'Giải quyết tranh chấp phát sinh tại các trung tâm xử lý đơn hàng Fulfillment Center.'
    ],
    perks: ['Môi trường thương mại điện tử chuyên nghiệp', 'Mua sắm Tiki ưu đãi nội bộ'],
    aiMatch: 90
  },
  {
    id: 521,
    title: 'Chuyên Viên Tuyển Dụng & Đào Tạo Tiếp Viên Hàng Không',
    company: 'Công ty Cổ phần Hàng không Vietjet (Vietjet Air)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM & Hà Nội',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 18, evaluated14d: 17, responseRate: 94, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['Tuyển dụng hàng không', 'Đánh giá ngoại hình/ngoại ngữ', 'Phỏng vấn cabin crew', 'Tổ chức casting'],
    jdSummary: [
      'Tổ chức các đợt thi tuyển tiếp viên hàng không tại các thành phố lớn trên cả nước và khu vực.',
      'Đánh giá các tiêu chuẩn khắt khe về ngoại ngữ, kỹ năng giao tiếp và khả năng phản ứng tình huống.',
      'Điều phối khóa đào tạo nghiệp vụ an toàn bay tại Học viện Hàng không Vietjet.'
    ],
    perks: ['Vé máy bay miễn phí không giới hạn tuyến bay nội địa và quốc tế', 'Môi trường đa văn hóa'],
    aiMatch: 91
  },
  {
    id: 522,
    title: 'Quản Lý Nhân Sự Vùng (Regional HR Manager FMCG)',
    company: 'Công ty Cổ phần Viễn thông FPT (FPT Telecom)',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '26 - 42 triệu',
    salaryIsOrange: false,
    location: 'Đà Nẵng & Miền Trung',
    city: 'Đà Nẵng',
    exp: '3-5 năm',
    level: 'Trưởng phòng vùng',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['Regional HR', 'Quản lý nhân sự chi nhánh tỉnh', 'Tuyển dụng diện rộng', 'Chính sách địa phương'],
    jdSummary: [
      'Quản lý công tác nhân sự cho hơn 12 chi nhánh FPT Telecom tại các tỉnh miền Trung.',
      'Chỉ đạo hoàn thành chỉ tiêu tuyển dụng nhân viên kinh doanh và kỹ thuật viên bảo trì mạng lưới.',
      'Kiểm tra định kỳ việc thực thi chính sách chế độ của CBNV theo đúng chuẩn tập đoàn.'
    ],
    perks: ['Chế độ phúc lợi FPT Care', 'Thưởng hoàn thành mục tiêu kinh doanh vùng'],
    aiMatch: 89
  },
  {
    id: 523,
    title: 'Employer Branding & Future Leaders Program Specialist',
    company: 'Unilever Vietnam',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '8 giờ trước',
    verified: true,
    skills: ['Employer Branding', 'UFLP Management', 'University Relations', 'Hackathon/Case Competition'],
    jdSummary: [
      'Chủ trì chương trình Nhà Lãnh Đạo Tương Lai Unilever Future Leaders Program (UFLP) danh giá.',
      'Tổ chức cuộc thi giải quyết tình huống kinh doanh Unilever Future Leaders League cho sinh viên xuất sắc.',
      'Quản lý các kênh truyền thông tuyển dụng và duy trì vị thế Nơi làm việc tốt nhất Việt Nam.'
    ],
    perks: ['Môi trường phát triển nhân tài chuẩn tập đoàn FMCG số 1', 'Phúc lợi và bảo hiểm toàn diện'],
    aiMatch: 95
  },
  {
    id: 524,
    title: 'Trưởng Phòng Hành Chính Bệnh Viện & Quản Trị Cơ Sở Vật Chất',
    company: 'Hệ thống Y tế Vinmec (Vinmec Healthcare System)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'hr',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng phòng hành chính',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 92, lastReviewed: '12:00' },
    updated: '8 giờ trước',
    verified: true,
    skills: ['Quản trị hành chính y tế', 'Tiêu chuẩn quốc tế JCI', 'Facility Management', 'Quản lý an ninh/vệ sinh'],
    jdSummary: [
      'Quản lý toàn bộ công tác hành chính, hậu cần và cơ sở vật chất tại bệnh viện đa khoa quốc tế Vinmec.',
      'Đảm bảo các quy trình vệ sinh kiểm soát nhiễm khuẩn đạt chuẩn chất lượng quốc tế JCI nghiêm ngặt.',
      'Điều phối công tác khánh tiết, đón tiếp các đoàn chuyên gia y tế và bệnh nhân VIP.'
    ],
    perks: ['Gói chăm sóc y tế Vinmec đặc quyền cho bản thân và gia đình', 'Chế độ đãi ngộ vượt trội'],
    aiMatch: 91
  }
];

console.log('HR jobs generated:', hrJobs.length);
