const fs = require('fs');

const itJobs = [
  {
    id: 201,
    title: 'Senior Fullstack Engineer (ReactJS, Node.js & AWS)',
    company: 'FPT Software Global',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '30 - 48 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội (Cầu Giấy)',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Hybrid',
    isLightningBadge: true,
    lightningStats: { applied30d: 25, evaluated14d: 24, responseRate: 96, lastReviewed: '12:00' },
    updated: '10 phút trước',
    verified: true,
    skills: ['ReactJS', 'Node.js', 'TypeScript', 'AWS Microservices'],
    jdSummary: [
      'Thiết kế kiến trúc hệ thống và phát triển nền tảng FinTech quy mô hàng triệu users.',
      'Tối ưu hóa hiệu năng render phía client và API throughput phía backend.',
      'Review code và hướng dẫn chuyên môn cho các kỹ sư cấp dưới.'
    ],
    perks: ['Chế độ làm việc linh hoạt Hybrid', 'Cơ hội onsite ngắn hạn tại Nhật Bản và Singapore'],
    aiMatch: 98
  },
  {
    id: 202,
    title: 'Principal Software Architect (AI Camera & Mobile OS)',
    company: 'Samsung R&D Institute Vietnam (SRV)',
    logo: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '55 - 85 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội (Tây Hồ)',
    city: 'Hà Nội',
    exp: 'Trên 5 năm',
    level: 'Architect / Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '25 phút trước',
    verified: true,
    skills: ['System Architecture', 'C/C++', 'AI Algorithms', 'Mobile OS Platform'],
    jdSummary: [
      'Chủ trì thiết kế kiến trúc phần mềm lõi cho camera thông minh trên các dòng flagship.',
      'Nghiên cứu áp dụng các mô hình học sâu (Deep Learning) tối ưu trên chip bán dẫn NPU.',
      'Phối hợp với trung tâm R&D tại Hàn Quốc để đồng bộ tiêu chuẩn kỹ thuật.'
    ],
    perks: ['Gói lương thưởng cạnh tranh bậc nhất ngành công nghệ', 'Xe đưa đón CBNV khắp Hà Nội'],
    aiMatch: 95
  },
  {
    id: 203,
    title: 'Senior Backend Engineer (Golang, Microservices)',
    company: 'VNG Corporation',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '35 - 55 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM (Quận 7)',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 19, evaluated14d: 17, responseRate: 89, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Golang', 'Distributed Systems', 'Kafka', 'Redis Cluster', 'K8s'],
    jdSummary: [
      'Xây dựng các dịch vụ microservices chịu tải cao (High Concurrency) phục vụ ZaloPay & Games.',
      'Thiết kế cơ chế cache đa tầng và tối ưu hóa truy vấn dữ liệu phân tán.',
      'Đảm bảo hệ thống đạt độ sẵn sàng cao 99.99% (High Availability).'
    ],
    perks: ['Ăn trưa miễn phí tại VNG Campus', 'Khu phức hợp thể thao, gym và hồ bơi nội bộ'],
    aiMatch: 94
  },
  {
    id: 204,
    title: 'AI Research Scientist / Computer Vision Specialist',
    company: 'VinAI Research',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '40 - 75 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Chuyên gia nghiên cứu',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 10, responseRate: 83, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Computer Vision', 'PyTorch', 'Autonomous Driving', 'Deep Learning'],
    jdSummary: [
      'Nghiên cứu các thuật toán thị giác máy tính cho hệ thống lái xe tự hành Smart Mobility.',
      'Công bố các bài báo khoa học tại các hội nghị hàng đầu thế giới (CVPR, ICCV, NeurIPS).',
      'Triển khai mô hình AI chạy thực tế trên hệ thống xe điện thông minh.'
    ],
    perks: ['Tài nguyên siêu máy tính GPU NVIDIA A100 không giới hạn', 'Tài trợ tham dự hội thảo quốc tế'],
    aiMatch: 91
  },
  {
    id: 205,
    title: 'Senior DevOps / Cloud Platform Engineer (AWS, K8s)',
    company: 'One Mount Group',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '32 - 50 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Hybrid',
    isLightningBadge: false,
    lightningStats: { applied30d: 14, evaluated14d: 10, responseRate: 71, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Kubernetes', 'Terraform', 'CI/CD Pipeline', 'AWS Security'],
    jdSummary: [
      'Quản lý hạ tầng đám mây đa dịch vụ phục vụ hệ sinh thái VinID và VinShop.',
      'Tự động hóa hoàn toàn quy trình CI/CD từ dev sang production.',
      'Giám sát hệ thống với Prometheus, Grafana và phản ứng sự cố 24/7.'
    ],
    perks: ['Gói khám sức khỏe cao cấp tại Vinmec', 'Làm việc linh hoạt 2 ngày WFH'],
    aiMatch: 87
  },
  {
    id: 206,
    title: 'Tech Lead Mobile Engineer (Flutter & Native)',
    company: 'MoMo Fintech (M-Service)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '40 - 60 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: 'Trên 5 năm',
    level: 'Tech Lead',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Flutter', 'iOS (Swift)', 'Android (Kotlin)', 'Clean Architecture'],
    jdSummary: [
      'Dẫn dắt đội ngũ kỹ sư mobile phát triển các mini-apps trên siêu ứng dụng MoMo.',
      'Định hình chuẩn kiến trúc Mobile Clean Architecture và tối ưu hóa thời gian mở app.',
      'Phối hợp với Product Team để mang lại trải nghiệm UX mượt mà 60fps.'
    ],
    perks: ['Thưởng cổ phiếu ESOP theo hiệu quả công việc', 'Bảo hiểm PVI gia đình'],
    aiMatch: 95
  },
  {
    id: 207,
    title: 'Kỹ Sư Giải Pháp Mạng 5G & Cloud Core (Senior Network Engineer)',
    company: 'Tổng Công ty Mạng lưới Viettel (Viettel Networks)',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '30 - 52 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '20 phút trước',
    verified: true,
    skills: ['5G Core Network', 'NFV/SDN', 'OpenRAN', 'Cisco/Juniper CCNP'],
    jdSummary: [
      'Thiết kế và tối ưu mạng lõi 5G SA (Standalone) phục vụ hạ tầng viễn thông quốc gia.',
      'Triển khai ảo hóa mạng (Network Functions Virtualization) trên nền tảng OpenStack.',
      'Khắc phục sự cố mạng mức L3 và đảm bảo an toàn an ninh mạng viễn thông.'
    ],
    perks: ['Môi trường nghiên cứu công nghệ hàng đầu', 'Chính sách đãi ngộ vượt trội của Viettel'],
    aiMatch: 93
  },
  {
    id: 208,
    title: 'Principal Java Engineer (Core Banking Microservices)',
    company: 'Ngân hàng Techcombank',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '45 - 70 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: 'Trên 5 năm',
    level: 'Principal / Lead',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 18, evaluated14d: 17, responseRate: 94, lastReviewed: '12:00' },
    updated: '35 phút trước',
    verified: true,
    skills: ['Java 21', 'Spring Boot 3', 'Kafka Event-Driven', 'PostgreSQL Distributed'],
    jdSummary: [
      'Thiết kế kiến trúc hệ thống Core Banking thế hệ mới phục vụ chuyển đổi số Techcombank.',
      'Đảm bảo chuẩn tuân thủ bảo mật tài chính ngân hàng (PCI-DSS, ISO 27001).',
      'Cố vấn kỹ thuật và xây dựng chuẩn mã nguồn cho 50+ kỹ sư phần mềm.'
    ],
    perks: ['Thưởng hiệu quả hàng năm hấp dẫn', 'Bảo hiểm sức khỏe cao cấp toàn diện'],
    aiMatch: 97
  },
  {
    id: 209,
    title: 'Senior Frontend Developer (Vue.js / Nuxt.js & Micro-Frontend)',
    company: 'Công ty Công nghệ Thông tin VNPT (VNPT-IT)',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '25 - 42 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '50 phút trước',
    verified: true,
    skills: ['Vue.js 3', 'Nuxt.js', 'TypeScript', 'Module Federation', 'TailwindCSS'],
    jdSummary: [
      'Phát triển cổng dịch vụ công quốc gia và hệ thống phần mềm quản lý y tế VNPT-eGov.',
      'Xây dựng kiến trúc Micro-Frontend giúp các module phát triển và triển khai độc lập.',
      'Tối ưu hóa khả năng truy cập Accessibility (a11y) và tốc độ tải trang Core Web Vitals.'
    ],
    perks: ['Phúc lợi ổn định, thưởng dự án chính phủ', 'Hỗ trợ đào tạo chứng chỉ quốc tế'],
    aiMatch: 91
  },
  {
    id: 210,
    title: 'Data Infrastructure Engineer (Kafka, Spark & ClickHouse)',
    company: 'Shopee Vietnam',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '35 - 58 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM (Quận 7)',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 92, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Big Data', 'Apache Spark', 'Kafka Streaming', 'ClickHouse', 'Hadoop HDFS'],
    jdSummary: [
      'Vận hành cụm dữ liệu phân tán quy mô Petabytes xử lý hàng tỷ đơn hàng mỗi ngày.',
      'Tối ưu hóa pipeline streaming thời gian thực phục vụ báo cáo doanh thu Mega Campaign.',
      'Phối hợp với Data Science Team để tối ưu hóa truy vấn dữ liệu lớn.'
    ],
    perks: ['Môi trường chuẩn Silicon Valley', 'MacBook Pro M3 Max và trợ cấp công việc'],
    aiMatch: 94
  },
  {
    id: 211,
    title: 'Senior C++ Engineer (Real-time Audio/Video Streaming)',
    company: 'VNG Corporation (Zalo Platform)',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '38 - 60 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 10, evaluated14d: 9, responseRate: 90, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Modern C++', 'WebRTC', 'Media Codec (H.264/AV1)', 'Network Socket', 'Multithreading'],
    jdSummary: [
      'Tối ưu giao thức truyền tải âm thanh và hình ảnh cho tính năng gọi điện thoại Zalo Call.',
      'Xử lý độ trễ thấp (Ultra Low Latency) và khả năng thích ứng mạng yếu (Jitter Buffer).',
      'Viết mã nguồn tối ưu hóa hiệu năng CPU và tiết kiệm pin trên thiết bị di động.'
    ],
    perks: ['Làm việc trên sản phẩm phục vụ 75 triệu người dùng', 'Thưởng performance theo quý'],
    aiMatch: 96
  },
  {
    id: 212,
    title: 'Embedded Linux Software Engineer (ADAS / Autonomous Car)',
    company: 'Tập đoàn VinFast Toàn Cầu',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '35 - 55 triệu',
    salaryIsOrange: false,
    location: 'Hải Phòng & Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Embedded C/C++', 'Yocto Linux', 'QNX RTOS', 'CAN Bus', 'AUTOSAR'],
    jdSummary: [
      'Phát triển phần mềm nhúng điều khiển hệ thống hỗ trợ lái xe nâng cao ADAS trên xe điện VinFast.',
      'Tích hợp cảm biến radar, lidar và camera nhận diện làn đường thời gian thực.',
      'Đảm bảo tiêu chuẩn an toàn chức năng ô tô quốc tế ISO 26262 (ASIL D).'
    ],
    perks: ['Ưu đãi mua ô tô điện VinFast đặc quyền', 'Xe đưa đón CBNV Hà Nội - Hải Phòng'],
    aiMatch: 92
  },
  {
    id: 213,
    title: 'Senior Mobile Developer (iOS Swift & Android Kotlin)',
    company: 'Ngân hàng TMCP Quân Đội (MB Bank)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '30 - 48 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 20, evaluated14d: 19, responseRate: 95, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Swift/SwiftUI', 'Kotlin/Jetpack Compose', 'Mobile Security', 'Biometrics eKYC'],
    jdSummary: [
      'Phát triển các tính năng chuyển khoản, đầu tư và tích điểm loyalty trên App MBBank.',
      'Tích hợp giải pháp xác thực sinh trắc học khuôn mặt eKYC bảo mật cao theo chuẩn NHNN.',
      'Tối ưu hóa trải nghiệm giao diện người dùng mượt mà và tương thích đa kích thước màn hình.'
    ],
    perks: ['Thưởng cuối năm 4-6 tháng lương', 'Chế độ phụ cấp công nghệ hàng tháng'],
    aiMatch: 95
  },
  {
    id: 214,
    title: 'Senior Security Engineer (SOC & Red Team Penetration Testing)',
    company: 'Công ty An ninh mạng CMC (CMC Cyber Security)',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Penetration Testing', 'SIEM / SOC', 'CEH / OSCP', 'Reverse Engineering', 'Malware Analysis'],
    jdSummary: [
      'Thực hiện kiểm thử xâm nhập (Pentest) định kỳ cho các hệ thống ngân hàng và cơ quan chính phủ.',
      'Giám sát và phân tích các cuộc tấn công mạng DDoS, Ransomware trên trung tâm SOC.',
      'Xây dựng quy trình ứng cứu sự cố bảo mật thông tin chuẩn quốc tế.'
    ],
    perks: ['Được tài trợ 100% lệ phí thi chứng chỉ quốc tế OSCP/CISSP', 'Môi trường an ninh mạng top 1'],
    aiMatch: 90
  },
  {
    id: 215,
    title: 'Lead Data Engineer (Real-time Recommendation Engine)',
    company: 'Tiki Corporation',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '40 - 62 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: 'Trên 5 năm',
    level: 'Lead / Principal',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Data Architecture', 'Flink Streaming', 'Vector DB (Milvus)', 'Python', 'Airflow'],
    jdSummary: [
      'Chủ trì kiến trúc nền tảng dữ liệu gợi ý sản phẩm cá nhân hóa theo hành vi người dùng.',
      'Xây dựng luồng xử lý dữ liệu thời gian thực với Apache Flink và lưu trữ trên Vector Database.',
      'Dẫn dắt đội ngũ 6 kỹ sư dữ liệu tối ưu hóa thời gian tính toán model từ vài giờ xuống mili-giây.'
    ],
    perks: ['Chế độ cổ phiếu ESOP hấp dẫn', 'Bảo hiểm sức khỏe quốc tế'],
    aiMatch: 93
  },
  {
    id: 216,
    title: 'Senior Backend Engineer (Go & High Concurrency Dispatch)',
    company: 'Công ty Cổ phần Be Group',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '32 - 50 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Golang', 'Geo-spatial Indexing', 'Redis Cluster', 'High Concurrency', 'Docker/K8s'],
    jdSummary: [
      'Thiết kế thuật toán điều phối xe (Ride Matching) tối ưu khoảng cách và thời gian đón khách.',
      'Xử lý hàng trăm nghìn truy vấn tìm xe đồng thời vào các khung giờ cao điểm và mưa bão.',
      'Tối ưu hóa kiến trúc hạ tầng giảm thiểu chi phí máy chủ đám mây AWS.'
    ],
    perks: ['Gói di chuyển Be miễn phí', 'Thưởng nóng dự án phát triển công nghệ mới'],
    aiMatch: 92
  },
  {
    id: 217,
    title: 'Chuyên Gia Giải Pháp ERP SAP S/4HANA (Lead SAP Consultant)',
    company: 'Công ty Hệ thống Thông tin FPT (FPT IS)',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '35 - 55 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Chuyên gia cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 92, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['SAP S/4HANA', 'FI/CO Module', 'Tư vấn triển khai ERP', 'Thiết kế quy trình doanh nghiệp'],
    jdSummary: [
      'Chủ trì tư vấn và triển khai giải pháp ERP SAP S/4HANA cho các tập đoàn sản xuất lớn.',
      'Khảo sát yêu cầu nghiệp vụ tài chính, chuỗi cung ứng và thiết kế cấu hình phân hệ FI/CO.',
      'Đào tạo chuyển giao công nghệ và hỗ trợ người dùng go-live thành công.'
    ],
    perks: ['Thưởng dự án theo từng giai đoạn nghiệm thu', 'Bảo hiểm FPT Care'],
    aiMatch: 91
  },
  {
    id: 218,
    title: 'Kỹ Sư An Toàn Thông Tin & Phòng Chống Gian Lận (CyberSec Fraud Detection)',
    company: 'Ngân hàng TMCP Ngoại Thương Việt Nam (Vietcombank)',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '30 - 48 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 17, evaluated14d: 16, responseRate: 94, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Fraud Detection', 'AI Pattern Recognition', 'An toàn giao dịch thẻ', 'PCI-DSS'],
    jdSummary: [
      'Xây dựng hệ thống cảnh báo sớm giao dịch đáng ngờ và ngăn chặn gian lận thẻ tín dụng trực tuyến.',
      'Ứng dụng học máy (Machine Learning) để phát hiện tài khoản bất thường theo thời gian thực.',
      'Đảm bảo tuyệt đối an toàn bảo mật tài sản cho hàng chục triệu khách hàng Vietcombank.'
    ],
    perks: ['Môi trường chuẩn ngân hàng nhà nước số 1', 'Chế độ đãi ngộ vượt trội dài hạn'],
    aiMatch: 95
  },
  {
    id: 219,
    title: 'Senior Python / AI Engineer (LLM & CV Matching Model)',
    company: 'TopCV Vietnam',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '30 - 50 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 22, evaluated14d: 21, responseRate: 95, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Python FastApi', 'LangChain', 'OpenAI/Anthropic API', 'Semantic Search', 'Vector DB'],
    jdSummary: [
      'Phát triển mô hình AI phân tích hồ sơ ứng viên và khớp nối tự động với yêu cầu tuyển dụng.',
      'Tối ưu hóa thuật toán tìm kiếm ngữ nghĩa (Semantic Search) giúp gợi ý việc làm chính xác.',
      'Xây dựng hệ thống prompt engineering và fine-tune mô hình ngôn ngữ lớn (LLM).'
    ],
    perks: ['Được làm việc với dữ liệu tuyển dụng lớn nhất Việt Nam', 'Môi trường làm việc trẻ trung sáng tạo'],
    aiMatch: 94
  },
  {
    id: 220,
    title: 'Senior Cloud Architect (AWS & Google Cloud Platform)',
    company: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '40 - 65 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: 'Trên 5 năm',
    level: 'Architect / Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['AWS Solutions Architect', 'GCP Multi-cloud', 'Landing Zone', 'FinOps', 'IaC Terraform'],
    jdSummary: [
      'Hoạch định chiến lược chuyển đổi toàn bộ ứng dụng ngân hàng lên hạ tầng đám mây đa nền tảng.',
      'Thiết kế kiến trúc mạng ảo (VPC/Direct Connect) và hệ thống phân quyền IAM an toàn tuyệt đối.',
      'Áp dụng thực hành FinOps tối ưu hóa chi phí vận hành hạ tầng đám mây định kỳ.'
    ],
    perks: ['Gói thu nhập hấp dẫn thuộc top đầu thị trường', 'Cơ hội thăng tiến lên Head of Cloud'],
    aiMatch: 96
  },
  {
    id: 221,
    title: 'Lead Automation QA Engineer (Playwright, Selenium & CI/CD)',
    company: 'TMA Solutions',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '26 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM & Bình Định',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Lead QA',
    type: 'Hybrid',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['Playwright', 'Selenium WebDriver', 'Java/TypeScript', 'Jenkins Pipeline', 'Performance Testing'],
    jdSummary: [
      'Xây dựng framework kiểm thử tự động hóa toàn diện từ API đến End-to-End UI.',
      'Tích hợp bộ kiểm thử tự động vào quy trình CI/CD đảm bảo chất lượng release hàng tuần.',
      'Đào tạo và nâng cao năng lực viết test automation cho đội ngũ kiểm thử phần mềm.'
    ],
    perks: ['Chế độ onsite Bắc Mỹ và châu Âu', 'Môi trường làm việc năng động bền vững'],
    aiMatch: 89
  },
  {
    id: 222,
    title: 'Senior Fullstack Developer (.NET Core & Angular)',
    company: 'KMS Technology',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM & Đà Nẵng',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['.NET 8 C#', 'Angular 17', 'SQL Server Enterprise', 'Azure DevOps', 'Clean Code'],
    jdSummary: [
      'Phát triển các sản phẩm phần mềm SaaS phục vụ khách hàng doanh nghiệp tại thị trường Mỹ.',
      'Xây dựng kiến trúc RESTful API chuẩn mực và tối ưu hóa xử lý cơ sở dữ liệu lớn.',
      'Thực hiện code review và đảm bảo độ bao phủ unit test đạt tối thiểu 80%.'
    ],
    perks: ['Gói bảo hiểm sức khỏe quốc tế cao cấp', 'Phụ cấp học tiếng Anh và chứng chỉ Microsoft'],
    aiMatch: 92
  },
  {
    id: 223,
    title: 'Senior Solutions Architect (Enterprise FinTech)',
    company: 'NashTech Vietnam',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '45 - 68 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: 'Trên 5 năm',
    level: 'Solutions Architect',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['Solutions Architecture', 'FinTech Platforms', 'Domain-Driven Design', 'Cloud Native'],
    jdSummary: [
      'Tư vấn kiến trúc công nghệ toàn diện cho các định chế tài chính và ngân hàng tại Anh Quốc và Úc.',
      'Thiết kế hệ thống thanh toán xuyên biên giới với khả năng mở rộng quy mô lớn.',
      'Lãnh đạo kỹ thuật cho các đội ngũ phát triển đa quốc gia.'
    ],
    perks: ['Cơ hội công tác tại văn phòng Luân Đôn định kỳ', 'Gói lương thưởng cạnh tranh quốc tế'],
    aiMatch: 95
  },
  {
    id: 224,
    title: 'Senior Java Backend Engineer (Payment Gateway & Core QR)',
    company: 'Công ty Cổ phần Giải pháp Thanh toán Việt Nam (VNPAY)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'it',
    salaryBadge: '30 - 50 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 19, evaluated14d: 18, responseRate: 95, lastReviewed: '12:00' },
    updated: '8 giờ trước',
    verified: true,
    skills: ['Java Core', 'High Throughput Gateway', 'ISO 8583 Message', 'PostgreSQL', 'Redis'],
    jdSummary: [
      'Phát triển hệ thống xử lý giao dịch cổng thanh toán VNPAY-QR kết nối hơn 40 ngân hàng.',
      'Tối ưu hóa thời gian xử lý giao dịch dưới 200ms với độ tin cậy tuyệt đối 99.999%.',
      'Đảm bảo các tiêu chuẩn mã hóa dữ liệu nhạy cảm của khách hàng.'
    ],
    perks: ['Thưởng Tết và thưởng dự án hàng đầu ngành FinTech', 'Gói khám sức khỏe toàn diện'],
    aiMatch: 94
  }
];

console.log('IT jobs generated:', itJobs.length);
