const fs = require('fs');

const marketingJobs = [
  {
    id: 301,
    title: 'Trưởng Nhóm Digital Marketing & Performance Ads',
    company: 'VNG Corporation (Zalo)',
    logo: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '28 - 42 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 14, responseRate: 87, lastReviewed: '12:00' },
    updated: '20 phút trước',
    verified: true,
    skills: ['Performance Marketing', 'Meta Ads', 'Google Ads', 'Data Analytics', 'CRO'],
    jdSummary: [
      'Quản lý ngân sách Digital Ads hàng tháng cho các sản phẩm công nghệ trọng điểm.',
      'Tối ưu hóa phễu chuyển đổi (Funnel Optimization) và chỉ số CAC / LTV.',
      'Phối hợp với Creative Team để A/B testing thông điệp truyền thông.'
    ],
    perks: ['Môi trường năng động số 1 ngành Tech', 'Ngân sách thử nghiệm chiến dịch lớn'],
    aiMatch: 93
  },
  {
    id: 302,
    title: 'Senior Brand Manager (Ngành Tiêu Dùng FMCG)',
    company: 'Masan Consumer Holdings',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '35 - 55 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: 'Trên 5 năm',
    level: 'Trưởng phòng / Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 17, evaluated14d: 16, responseRate: 94, lastReviewed: '12:00' },
    updated: '45 phút trước',
    verified: true,
    skills: ['Brand Strategy', 'Product Launch', 'Trade Marketing', 'Quản trị ngân sách'],
    jdSummary: [
      'Xây dựng chiến lược định vị và phát triển thị phần thương hiệu quốc gia.',
      'Lập kế hoạch ra mắt sản phẩm mới (NPD) trên mạng lưới phân phối toàn quốc.',
      'Đo lường sức khỏe thương hiệu (Brand Health Tracking) định kỳ hàng quý.'
    ],
    perks: ['Thưởng doanh số năm cạnh tranh', 'Chính sách mua sản phẩm Masan ưu đãi cao'],
    aiMatch: 95
  },
  {
    id: 303,
    title: 'Chuyên Viên SEO & Growth Marketing',
    company: 'Shopee Vietnam',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '20 - 32 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 9, responseRate: 82, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Technical SEO', 'Keyword Research', 'Google Analytics 4', 'Content Strategy'],
    jdSummary: [
      'Tối ưu hóa thứ hạng tìm kiếm tự nhiên của hàng triệu trang sản phẩm ngành hàng.',
      'Nghiên cứu xu hướng từ khóa mùa vụ và chỉ đạo nội dung bài viết chất lượng.',
      'Phân tích lưu lượng organic traffic và tỷ lệ thoát trang.'
    ],
    perks: ['Làm việc cùng các chuyên gia SEO đầu ngành khu vực Đông Nam Á', 'Thưởng dự án Mega Sale'],
    aiMatch: 89
  },
  {
    id: 304,
    title: 'Public Relations (PR) & Communications Manager',
    company: 'Tập đoàn VinFast Toàn Cầu',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '30 - 50 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 10, evaluated14d: 9, responseRate: 90, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Quan hệ báo chí', 'Quản trị khủng hoảng truyền thông', 'Thông cáo báo chí', 'Event PR'],
    jdSummary: [
      'Xây dựng mối quan hệ bền vững với các cơ quan thông tấn báo chí trong và ngoài nước.',
      'Soạn thảo các thông cáo báo chí, bài phát biểu cho lãnh đạo cấp cao của tập đoàn.',
      'Chủ động phát hiện và xử lý khủng hoảng truyền thông mạng xã hội 24/7.'
    ],
    perks: ['Ưu đãi mua ô tô điện VinFast đặc quyền', 'Môi trường toàn cầu chuyên nghiệp'],
    aiMatch: 92
  },
  {
    id: 305,
    title: 'Content Marketing Lead & Social Creative',
    company: 'Sun Group Corporation',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'Đà Nẵng & Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: false,
    lightningStats: { applied30d: 13, evaluated14d: 9, responseRate: 69, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Content Direction', 'Viral Video', 'TikTok Marketing', 'Storytelling Du lịch'],
    jdSummary: [
      'Chịu trách nhiệm định hướng nội dung sáng tạo cho các điểm đến Sun World.',
      'Sản xuất video ngắn triệu view trên TikTok, YouTube Shorts và Facebook Reels.',
      'Quản lý chất lượng bài viết của đội ngũ copywriter và agency bên ngoài.'
    ],
    perks: ['Vé tham quan miễn phí các công viên Sun World', 'Nghỉ dưỡng Sun Hospitality hàng năm'],
    aiMatch: 86
  },
  {
    id: 306,
    title: 'Senior Media Planner & Account Manager',
    company: 'Dentsu Redder Vietnam',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '25 - 38 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Senior',
    type: 'Hybrid',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 10, responseRate: 83, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['Media Planning', 'Agency Account', 'Đàm phán Booking', 'Chiến dịch 360'],
    jdSummary: [
      'Tư vấn kế hoạch truyền thông tích hợp (Integrated Media Plan) cho các thương hiệu Fortune 500.',
      'Phân bổ ngân sách truyền thông trên các kênh truyền hình, OOH và digital platforms.',
      'Điều phối tiến độ chiến dịch và nghiệm thu KPI truyền thông với khách hàng.'
    ],
    perks: ['Được vinh danh tại các giải thưởng ngành truyền thông', 'Môi trường Agency trẻ trung'],
    aiMatch: 90
  },
  {
    id: 307,
    title: 'Trưởng Phòng Truyền Thông & Tiếp Thị Kỹ Thuật Số',
    company: 'Công ty Cổ phần Viễn thông FPT (FPT Telecom)',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '30 - 48 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng phòng',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '25 phút trước',
    verified: true,
    skills: ['Digital Strategy', 'Omnichannel Marketing', 'Quản lý ngân sách', 'Brand Awareness'],
    jdSummary: [
      'Hoạch định chiến lược tiếp thị đa kênh cho các dòng sản phẩm Internet, FPT Camera và Smart Home.',
      'Quản lý ngân sách Digital Marketing hàng chục tỷ đồng mỗi năm.',
      'Lãnh đạo đội ngũ 12 chuyên viên tiếp thị số và truyền thông thương hiệu.'
    ],
    perks: ['Chế độ phúc lợi tập đoàn FPT toàn diện', 'Thưởng hoàn thành kế hoạch năm'],
    aiMatch: 94
  },
  {
    id: 308,
    title: 'Quản Lý Chiến Dịch Marketing Chuỗi Bách Hóa Xanh',
    company: 'Công ty Cổ phần Đầu tư Thế Giới Di Động (MWG)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Quản lý chiến dịch',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '40 phút trước',
    verified: true,
    skills: ['Retail Marketing', 'Khuyến mãi chuỗi', 'Trade Marketing', 'Phân tích hành vi mua sắm'],
    jdSummary: [
      'Lên kế hoạch và triển khai các chiến dịch khuyến mãi lớn tại hơn 1.700 điểm bán Bách Hóa Xanh.',
      'Phối hợp với bộ phận thu mua (Buying) đàm phán quyền lợi tài trợ từ các nhà cung cấp lớn.',
      'Đo lường hiệu quả tăng trưởng lượt khách ghé cửa hàng (Footfall Traffic) và giá trị giỏ hàng.'
    ],
    perks: ['Gói cổ phiếu thưởng ESOP thường niên', 'Môi trường làm việc năng động thực chiến'],
    aiMatch: 93
  },
  {
    id: 309,
    title: 'Brand Experience & Employer Branding Specialist',
    company: 'Ngân hàng Techcombank',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '22 - 36 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Employer Branding', 'Trải nghiệm thương hiệu', 'Tổ chức sự kiện', 'Sáng tạo nội dung'],
    jdSummary: [
      'Xây dựng hình ảnh Thương hiệu Nhà tuyển dụng số 1 ngành ngân hàng qua các chiến dịch truyền thông.',
      'Tổ chức các sự kiện trải nghiệm thương hiệu (Techcombank Marathon, Tech Day).',
      'Đo lường mức độ tương tác và nhận diện thương hiệu trên các kênh mạng xã hội chuyên nghiệp.'
    ],
    perks: ['Môi trường ngân hàng chuyển đổi số xuất sắc', 'Bảo hiểm chăm sóc sức khỏe gia đình'],
    aiMatch: 91
  },
  {
    id: 310,
    title: 'Senior Growth Marketing Manager (Acquisition & Retention)',
    company: 'Grab Vietnam',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '35 - 55 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior Manager',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Growth Marketing', 'User Acquisition', 'Retention Funnel', 'A/B Testing', 'SQL'],
    jdSummary: [
      'Phát triển các chiến lược tăng trưởng người dùng mới cho dịch vụ GrabFood và GrabMart.',
      'Thiết kế các chương trình khách hàng thân thiết và thử nghiệm mã ưu đãi cá nhân hóa.',
      'Tối ưu hóa chi phí thu hút khách hàng (CAC) và giá trị vòng đời (LTV).'
    ],
    perks: ['Gói phụ cấp GrabCredits hàng tháng', 'Cơ hội thăng tiến khu vực Đông Nam Á'],
    aiMatch: 95
  },
  {
    id: 311,
    title: 'Trưởng Nhóm Marketing Kỹ Thuật Số & B2B Branding',
    company: 'Tổng Công ty Cổ phần Bưu chính Viettel (Viettel Post)',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['B2B Marketing', 'Logistics Branding', 'Lead Generation', 'Chiến dịch số'],
    jdSummary: [
      'Định vị thương hiệu Viettel Post là đối tác chuyển phát logistics công nghệ tin cậy hàng đầu.',
      'Triển khai các chiến dịch tìm kiếm khách hàng doanh nghiệp thương mại điện tử lớn.',
      'Sản xuất các tài liệu giới thiệu giải pháp logistics thông minh (Case Study, Whitepaper).'
    ],
    perks: ['Chế độ đãi ngộ quân đội kỷ luật và chuyên nghiệp', 'Thưởng thành tích quý'],
    aiMatch: 90
  },
  {
    id: 312,
    title: 'Creative Lead & Copywriter (Chiến Dịch Siêu Ứng Dụng MoMo)',
    company: 'Công ty Cổ phần Dịch vụ Di động Trực tuyến (MoMo)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Creative Lead',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 18, evaluated14d: 17, responseRate: 94, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Creative Concept', 'Copywriting viral', 'Gamification Marketing', 'Chiến dịch Tết'],
    jdSummary: [
      'Chủ trì ý tưởng sáng tạo cho chiến dịch Lắc Xì Tết và các ngày hội siêu deal hàng tháng.',
      'Sáng tạo slogan, kịch bản video viral và thông điệp truyền thông gây bão mạng xã hội.',
      'Định hình phong cách ngôn ngữ trẻ trung, hóm hỉnh và gần gũi của thương hiệu MoMo.'
    ],
    perks: ['Môi trường sáng tạo không giới hạn', 'Thưởng cổ phiếu ESOP định kỳ'],
    aiMatch: 94
  },
  {
    id: 313,
    title: 'Senior Account Executive (Integrated Communications Agency)',
    company: 'Ogilvy Vietnam',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Senior Account',
    type: 'Toàn thời gian',
    isLightningBadge: false,
    lightningStats: { applied30d: 12, evaluated14d: 9, responseRate: 75, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Client Management', 'Agency Pitching', 'Chiến dịch truyền thông 360', 'Creative Brief'],
    jdSummary: [
      'Quản lý mối quan hệ và tiếp nhận yêu cầu chiến dịch từ các nhãn hàng quốc tế đa quốc gia.',
      'Viết Creative Brief truyền cảm hứng cho đội ngũ thiết kế và sáng tạo nội dung.',
      'Điều phối tiến độ sản xuất TVC, digital assets và giám sát nghiệm thu hợp đồng.'
    ],
    perks: ['Môi trường Agency truyền thông số 1 thế giới', 'Cơ hội giải thưởng quốc tế Cannes Lions'],
    aiMatch: 88
  },
  {
    id: 314,
    title: 'Social Media & Community Manager (Kênh Be Xe Ô Tô / Xe Máy)',
    company: 'Công ty Cổ phần Be Group',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '20 - 32 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM & Hà Nội',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Community Building', 'Social Fanpage', 'Content Bắt Trend', 'Xử lý khủng hoảng'],
    jdSummary: [
      'Xây dựng và phát triển cộng đồng người dùng và tài xế Be trên Facebook và TikTok.',
      'Sáng tạo nội dung bắt trend hài hước thu hút hàng triệu lượt tương tác tự nhiên mỗi tuần.',
      'Lắng nghe phản hồi của người dùng và hỗ trợ giải đáp thắc mắc dịch vụ kịp thời.'
    ],
    perks: ['Gói di chuyển Be miễn phí', 'Môi trường làm việc cởi mở, thoải mái'],
    aiMatch: 89
  },
  {
    id: 315,
    title: 'Chuyên Viên Tiếp Thị Khách Hàng Cá Nhân (Retail Marketing)',
    company: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Retail Banking Marketing', 'Thẻ tín dụng Cashback', 'POSM tại quầy', 'Direct Marketing'],
    jdSummary: [
      'Lên kế hoạch truyền thông cho các sản phẩm mở thẻ tín dụng, tài khoản số đẹp VPBank NEO.',
      'Sản xuất các ấn phẩm truyền thông tại hệ thống hơn 250 chi nhánh toàn quốc.',
      'Theo dõi và đánh giá chi phí tiếp thị trên mỗi khách hàng mới đăng ký sử dụng dịch vụ.'
    ],
    perks: ['Lương thưởng cạnh tranh trong ngành ngân hàng', 'Cơ hội thăng tiến lên Trưởng nhóm'],
    aiMatch: 91
  },
  {
    id: 316,
    title: 'Quản Trị Thương Hiệu Ngành Hàng Sữa Tươi (Brand Manager)',
    company: 'Vinamilk - Công ty Cổ phần Sữa Việt Nam',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '32 - 50 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Quản lý thương hiệu',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 17, evaluated14d: 16, responseRate: 94, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Brand Equity', 'FMCG Marketing', 'Phân tích thị trường', 'Chiến dịch TVC'],
    jdSummary: [
      'Chịu trách nhiệm về định vị thương hiệu và thị phần dòng sản phẩm Sữa tươi 100% Vinamilk.',
      'Sản xuất các chiến dịch quảng cáo truyền hình TVC và chiến dịch số truyền tải thông điệp dinh dưỡng.',
      'Hợp tác chặt chẽ với Trade Marketing và Sales thúc đẩy sản lượng tiêu thụ toàn quốc.'
    ],
    perks: ['Làm việc tại doanh nghiệp sữa số 1 Việt Nam', 'Thưởng hoàn thành mục tiêu năm lớn'],
    aiMatch: 95
  },
  {
    id: 317,
    title: 'Creative Marketing Lead (Chiến Dịch Thương Hiệu Giày Quốc Dân)',
    company: 'Công ty TNHH SX HTD Bình Tiên (Biti\'s Vietnam)',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Creative Strategy', 'Chiến dịch Đi Để Trở Về', 'Văn hóa giới trẻ', 'Music Marketing'],
    jdSummary: [
      'Chủ trì định hướng ý tưởng sáng tạo cho thương hiệu Biti\'s Hunter và các bộ sưu tập thời trang mới.',
      'Hợp tác với các nghệ sĩ âm nhạc hàng đầu sản xuất MV và dự án văn hóa truyền cảm hứng.',
      'Giữ vững vị thế thương hiệu giày thể thao hàng đầu trong lòng giới trẻ Gen Z.'
    ],
    perks: ['Môi trường tôn vinh bản sắc sáng tạo Việt Nam', 'Sản phẩm Biti\'s ưu đãi nội bộ'],
    aiMatch: 92
  },
  {
    id: 318,
    title: 'Senior CRM & Lifecycle Marketing Specialist',
    company: 'Tiki Corporation',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '24 - 38 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Senior Specialist',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['CRM Automation', 'Email/App Push', 'RFM Segmentation', 'Tối ưu phễu mua lại'],
    jdSummary: [
      'Thiết lập kịch bản thông báo tự động (App Push, SMS, Email) theo vòng đời mua hàng.',
      'Phân tích dữ liệu phân khúc RFM để kích hoạt lại tệp khách hàng không hoạt động (Re-activation).',
      'Đo lường chỉ số mở thông báo (Open Rate), click (CTR) và doanh thu phát sinh trực tiếp.'
    ],
    perks: ['Môi trường Data-driven hiện đại', 'Cơ hội tiếp cận công cụ tự động hóa hàng đầu'],
    aiMatch: 90
  },
  {
    id: 319,
    title: 'Trưởng Bộ Phận Tổ Chức Sự Kiện & Tài Trợ Thương Hiệu',
    company: 'Ngân hàng TMCP Quân Đội (MB Bank)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '28 - 42 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng bộ phận',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['Event Production', 'Tài trợ thể thao/văn hóa', 'Quản lý ngân sách sự kiện', 'VIP Hospitality'],
    jdSummary: [
      'Chủ trì tổ chức các sự kiện quy mô lớn của ngân hàng (Hội nghị khách hàng, Giải chạy MB, Đại nhạc hội).',
      'Đàm phán quyền lợi tài trợ cho các giải đấu thể thao và chương trình truyền hình uy tín.',
      'Quản lý chất lượng nhà thầu sản xuất sân khấu và hậu cần sự kiện chuyên nghiệp.'
    ],
    perks: ['Chế độ đãi ngộ hàng đầu trong ngành tài chính', 'Thưởng các sự kiện đặc biệt'],
    aiMatch: 93
  },
  {
    id: 320,
    title: 'Digital Performance Specialist (Kênh Bán Vé Hàng Không Toàn Cầu)',
    company: 'Công ty Cổ phần Hàng không Vietjet (Vietjet Air)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '25 - 38 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 92, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['Global Digital Ads', 'Vé máy bay trực tuyến', 'Chuyển đổi ROAS', 'Google Search Flight'],
    jdSummary: [
      'Tối ưu hóa chiến dịch quảng cáo tìm kiếm và mạng xã hội tại các thị trường quốc tế (Úc, Ấn Độ, Nhật, Hàn).',
      'Gia tăng lượng đặt vé trực tiếp trên website và ứng dụng di động Vietjet Air.',
      'Phân tích dữ liệu theo mùa vụ du lịch và phản ứng nhanh với động thái giá vé đối thủ.'
    ],
    perks: ['Vé máy bay miễn phí thường niên cho nhân viên và gia đình', 'Môi trường làm việc đa quốc gia'],
    aiMatch: 89
  },
  {
    id: 321,
    title: 'Marketing Manager (Dự Án Bất Động Sản Hàng Hiệu Masterise)',
    company: 'Tập đoàn Masterise Homes',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '40 - 65 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'TP.HCM',
    exp: 'Trên 5 năm',
    level: 'Marketing Manager',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 10, evaluated14d: 9, responseRate: 90, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['Luxury Real Estate Marketing', 'Triển lãm quốc tế', 'Định vị bất động sản hàng hiệu', 'PR cao cấp'],
    jdSummary: [
      'Chịu trách nhiệm chiến lược tiếp thị tổng thể cho các siêu dự án bất động sản hàng hiệu.',
      'Hợp tác với các đối tác khách sạn quốc tế Marriott International và Ritz-Carlton.',
      'Tổ chức các sự kiện ra mắt độc quyền tại Hong Kong, Singapore và Dubai.'
    ],
    perks: ['Thu nhập và hoa hồng dự án dẫn đầu thị trường', 'Môi trường làm việc đẳng cấp quốc tế'],
    aiMatch: 94
  },
  {
    id: 322,
    title: 'Assistant Brand Manager (Ngành Chăm Sóc Cá Nhân)',
    company: 'Unilever Vietnam',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '26 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Assistant Brand Manager',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['Brand Development', 'FMCG Market Research', 'Kế hoạch truyền thông năm', 'Nielsen/Kantar Data'],
    jdSummary: [
      'Đồng hành cùng Brand Manager phát triển thị phần các nhãn hàng chăm sóc cá nhân (Dove, Lifebuoy, Sunsilk).',
      'Phân tích báo cáo dữ liệu thị trường Nielsen và hành vi mua sắm người tiêu dùng.',
      'Triển khai các chiến dịch ra mắt bao bì mới và công thức cải tiến.'
    ],
    perks: ['Trường đào tạo Marketing chuẩn mực quốc tế', 'Phúc lợi và gói bảo hiểm toàn diện'],
    aiMatch: 93
  },
  {
    id: 323,
    title: 'Senior Growth Marketing Specialist (Ví Điện Tử VNPAY & Dịch Vụ Taxi)',
    company: 'Công ty Cổ phần Giải pháp Thanh toán Việt Nam (VNPAY)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 17, evaluated14d: 16, responseRate: 94, lastReviewed: '12:00' },
    updated: '8 giờ trước',
    verified: true,
    skills: ['FinTech Growth', 'Khuyến mại VNPAY-Taxi', 'Co-marketing Ngân hàng', 'Tối ưu chuyển đổi'],
    jdSummary: [
      'Lập kế hoạch thúc đẩy số lượng giao dịch thanh toán VNPAY Taxi và đặt vé máy bay trên App ngân hàng.',
      'Phối hợp với các ngân hàng đối tác triển khai chương trình đồng tài trợ khuyến mại.',
      'Phân tích hành vi thanh toán không tiền mặt để tối ưu hóa ngân sách chiết khấu.'
    ],
    perks: ['Chế độ đãi ngộ hàng đầu trong ngành FinTech', 'Thưởng tháng lương thứ 13 và thưởng KPI'],
    aiMatch: 91
  },
  {
    id: 324,
    title: 'Trade Marketing Manager (Chuỗi Nhà Hàng Ẩm Thực Toàn Quốc)',
    company: 'Tập đoàn Golden Gate (Golden Gate Group)',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'marketing',
    salaryBadge: '30 - 48 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng phòng Trade MKT',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '8 giờ trước',
    verified: true,
    skills: ['F&B Trade Marketing', 'POSM chuỗi nhà hàng', 'Khuyến mại ẩm thực', 'Tối ưu doanh thu bàn'],
    jdSummary: [
      'Chịu trách nhiệm các hoạt động tiếp thị tại điểm bán cho hơn 400 nhà hàng (Gogi House, Kichi-Kichi, Manwah).',
      'Thiết kế và triển khai các combo ưu đãi giờ vàng nhằm tối ưu tỷ lệ lấp đầy bàn ăn.',
      'Hợp tác với các đối tác thanh toán và ngân hàng triển khai ưu đãi hoàn tiền cho thực khách.'
    ],
    perks: ['Ưu đãi giảm giá 30% tại toàn bộ hệ thống nhà hàng Golden Gate', 'Môi trường làm việc trẻ trung năng động'],
    aiMatch: 92
  }
];

console.log('Marketing jobs generated:', marketingJobs.length);
