const fs = require('fs');

const financeJobs = [
  {
    id: 401,
    title: 'Chuyên Viên Phân Tích Dữ Liệu Tài Chính (Data Analyst)',
    company: 'Ngân hàng TMCP Quân Đội (MB Bank)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 22, evaluated14d: 20, responseRate: 91, lastReviewed: '12:00' },
    updated: '15 phút trước',
    verified: true,
    skills: ['SQL', 'Power BI', 'Phân tích tín dụng', 'Mô hình tài chính', 'Python'],
    jdSummary: [
      'Xây dựng các dashboard tự động theo dõi danh mục tín dụng và tăng trưởng tài sản.',
      'Phân tích hành vi chi tiêu thẻ tín dụng để đề xuất chính sách phân khúc khách hàng.',
      'Phối hợp với khối Quản trị rủi ro phát triển mô hình chấm điểm tín dụng nội bộ.'
    ],
    perks: ['Gói vay ưu đãi lãi suất ngân hàng MB cho nhân viên', 'Thưởng cuối năm 4-6 tháng lương'],
    aiMatch: 94
  },
  {
    id: 402,
    title: 'Quản Lý Rủi Ro Tín Dụng Khách Hàng Doanh Nghiệp',
    company: 'Ngân hàng VPBank',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '30 - 45 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 12, responseRate: 86, lastReviewed: '12:00' },
    updated: '50 phút trước',
    verified: true,
    skills: ['Quản trị rủi ro', 'Thẩm định hồ sơ tín dụng', 'Basel II/III', 'Phân tích dòng tiền'],
    jdSummary: [
      'Thẩm định độc lập các khoản vay vốn trung và dài hạn của doanh nghiệp quy mô lớn.',
      'Đánh giá tính khả thi phương án kinh doanh và phương án tài sản đảm bảo nợ vay.',
      'Giám sát chặt chẽ các chỉ tiêu cảnh báo rủi ro sớm (Early Warning Signals).'
    ],
    perks: ['Chế độ đãi ngộ hàng đầu trong khối Ngân hàng TMCP', 'Bảo hiểm sức khỏe đặc quyền'],
    aiMatch: 92
  },
  {
    id: 403,
    title: 'Trưởng Phòng Thẩm Định Dự Án & Đầu Tư Trực Tiếp',
    company: 'Ngân hàng Techcombank',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '45 - 65 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: 'Trên 5 năm',
    level: 'Trưởng phòng',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Thẩm định đầu tư', 'Project Finance', 'M&A', 'Đàm phán hợp đồng tài trợ vốn'],
    jdSummary: [
      'Chủ trì thẩm định các dự án năng lượng tái tạo, hạ tầng và bất động sản công nghiệp.',
      'Xây dựng cấu trúc tài trợ vốn hợp vốn (Syndicated Loan) với các định chế tài chính quốc tế.',
      'Báo cáo và giải trình trước Hội đồng tín dụng và Quản lý rủi ro cấp cao.'
    ],
    perks: ['Thưởng hiệu quả dự án hàng năm hấp dẫn', 'Môi trường Agile chuyển đổi số số 1'],
    aiMatch: 96
  },
  {
    id: 404,
    title: 'Chuyên Viên Quản Lý Danh Mục Đầu Tư (Portfolio Manager)',
    company: 'Chứng khoán SSI (SSI Securities)',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 10, evaluated14d: 8, responseRate: 80, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Chứng khoán', 'CFA level 2+', 'Định giá cổ phiếu', 'Phân tích vĩ mô'],
    jdSummary: [
      'Quản lý danh mục tài sản ủy thác của khách hàng tổ chức và cá nhân có tài sản ròng cao.',
      'Phân tích định giá doanh nghiệp niêm yết bằng phương pháp DCF và P/E so sánh.',
      'Thiết lập chiến lược tái cơ cấu danh mục cổ phiếu phòng ngừa biến động thị trường.'
    ],
    perks: ['Hoa hồng quản lý quỹ tính theo Alpha vượt trội', 'Môi trường làm việc top đầu TTCK'],
    aiMatch: 91
  },
  {
    id: 405,
    title: 'Senior Internal Auditor (Kiểm Toán Nội Bộ Tài Chính)',
    company: 'Vinamilk - Công ty Cổ phần Sữa Việt Nam',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '26 - 38 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior',
    type: 'Toàn thời gian',
    isLightningBadge: false,
    lightningStats: { applied30d: 12, evaluated14d: 8, responseRate: 67, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Kiểm toán nội bộ', 'IFRS / VAS', 'Kiểm soát tuân thủ', 'ACCA / CPA'],
    jdSummary: [
      'Thực hiện các cuộc kiểm toán định kỳ đối với các chi nhánh, nhà máy và trang trại Vinamilk.',
      'Đánh giá hiệu lực của hệ thống kiểm soát nội bộ và đề xuất cải tiến quy trình kế toán.',
      'Lập báo cáo kiểm toán độc lập trình Ủy ban Kiểm toán trực thuộc HĐQT.'
    ],
    perks: ['Môi trường làm việc bền vững hàng đầu Việt Nam', 'Thưởng tháng 13 + thưởng hoàn thành KPI'],
    aiMatch: 88
  },
  {
    id: 406,
    title: 'Financial Planning & Analysis (FP&A) Specialist',
    company: 'Công ty Cổ phần Đầu tư Thế Giới Di Động (MWG)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['FP&A', 'Lập ngân sách', 'Phân tích P&L chuỗi bán lẻ', 'Excel nâng cao'],
    jdSummary: [
      'Xây dựng kế hoạch tài chính và ngân sách hoạt động hàng năm cho chuỗi bán lẻ.',
      'Theo dõi và phân tích biến động chi phí thực tế so với ngân sách đã phê duyệt.',
      'Đưa ra các phân tích cảnh báo biên lợi nhuận ròng cho Ban Điều Hành.'
    ],
    perks: ['Gói cổ phiếu thưởng ESOP thường niên', 'Cơ hội phát triển lên vị trí Finance Manager'],
    aiMatch: 89
  },
  {
    id: 407,
    title: 'Chuyên Viên Kinh Doanh Ngoại Hối & Phái Sinh (FX & Derivatives Trader)',
    company: 'Ngân hàng TMCP Ngoại Thương Việt Nam (Vietcombank)',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '30 - 55 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Trader / Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '30 phút trước',
    verified: true,
    skills: ['FX Trading', 'Phái sinh tỷ giá', 'Thị trường liên ngân hàng', 'Quản trị trạng thái ngoại hối'],
    jdSummary: [
      'Thực hiện các giao dịch mua bán ngoại tệ giao ngay (Spot), kỳ hạn (Forward) và hoán đổi (Swap).',
      'Cung cấp giải pháp phòng ngừa rủi ro biến động tỷ giá cho khách hàng doanh nghiệp xuất nhập khẩu.',
      'Duy trì hạn mức trạng thái ngoại tệ và tuân thủ chặt chẽ quy định của Ngân hàng Nhà nước.'
    ],
    perks: ['Thưởng hiệu quả giao dịch (P&L bonus) cạnh tranh', 'Môi trường kinh doanh tiền tệ số 1'],
    aiMatch: 95
  },
  {
    id: 408,
    title: 'Trưởng Phòng Quản Lý Tài Sản & Khách Hàng Ưu Tiên (Priority Wealth)',
    company: 'Ngân hàng TMCP Á Châu (ACB)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '35 - 55 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Trưởng phòng',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 18, evaluated14d: 17, responseRate: 94, lastReviewed: '12:00' },
    updated: '45 phút trước',
    verified: true,
    skills: ['Wealth Management', 'Tư vấn đầu tư trái phiếu', 'Chứng chỉ quỹ', 'Chăm sóc khách hàng VIP'],
    jdSummary: [
      'Điều hành phòng dịch vụ khách hàng ưu tiên ACB Privilege Banking.',
      'Thiết kế danh mục phân bổ tài sản an toàn và sinh lời bền vững cho khách hàng có số dư lớn.',
      'Quản lý tổng tài sản quản lý (AUM) tăng trưởng theo mục tiêu chiến lược của ngân hàng.'
    ],
    perks: ['Thưởng doanh số và hiệu quả quản lý hấp dẫn', 'Bảo hiểm sức khỏe đặc quyền ACB Care'],
    aiMatch: 93
  },
  {
    id: 409,
    title: 'Chuyên Viên Môi Giới & Tư Vấn Đầu Tư Khách Hàng VIP',
    company: 'Công ty Cổ phần Chứng khoán VPS',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '25 - 50 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 20, evaluated14d: 19, responseRate: 95, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Môi giới chứng khoán', 'Phân tích kỹ thuật TA', 'Tư vấn Margin', 'Quản trị rủi ro danh mục'],
    jdSummary: [
      'Cung cấp các bản tin khuyến nghị đầu tư cổ phiếu hàng ngày cho nhóm khách hàng giá trị cao.',
      'Hỗ trợ quản trị rủi ro danh mục và cơ cấu tỷ trọng margin hợp lý theo diễn biến thị trường.',
      'Mở rộng tệp nhà đầu tư cá nhân năng động trên nền tảng SmartOne.'
    ],
    perks: ['Tỷ lệ chia sẻ hoa hồng phí giao dịch cao nhất thị trường', 'Đào tạo phân tích độc quyền'],
    aiMatch: 92
  },
  {
    id: 410,
    title: 'Chuyên Viên Quản Trị Rủi Ro Thanh Khoản & Thị Trường',
    company: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '26 - 42 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Market Risk', 'Rủi ro thanh khoản', 'LCR / NSFR', 'Stress Testing', 'Mô hình VaR'],
    jdSummary: [
      'Đo lường và giám sát các chỉ số an toàn vốn và thanh khoản theo tiêu chuẩn Basel II & III.',
      'Thực hiện kiểm tra sức chịu đựng (Stress Testing) danh mục trái phiếu và lãi suất liên ngân hàng.',
      'Đề xuất các biện pháp phòng ngừa rủi ro biến động thị trường tài chính vĩ mô.'
    ],
    perks: ['Phúc lợi toàn diện và tính ổn định cao', 'Lộ trình phát triển chuyên gia phân tích rủi ro'],
    aiMatch: 90
  },
  {
    id: 411,
    title: 'Trưởng Nhóm Thẩm Định Tín Dụng Dự Án Năng Lượng Xanh',
    company: 'Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '30 - 48 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Thẩm định dự án điện gió/mặt trời', 'Tín dụng xanh ESG', 'Mô hình dòng tiền dự án', 'Bảo lãnh EPC'],
    jdSummary: [
      'Chủ trì thẩm định các dự án điện gió, điện mặt trời và hạ tầng khu công nghiệp xanh.',
      'Đánh giá các điều kiện hợp đồng mua bán điện (PPA) và khả năng trả nợ vay dài hạn.',
      'Kết nối nguồn vốn ưu đãi từ các định chế tài chính quốc tế như IFC, ADB.'
    ],
    perks: ['Chế độ đãi ngộ vượt trội', 'Môi trường làm việc thúc đẩy tài chính bền vững ESG'],
    aiMatch: 93
  },
  {
    id: 412,
    title: 'Senior Equity Research Analyst (Ngành Bất Động Sản & Bán Lẻ)',
    company: 'Quỹ Đầu tư Dragon Capital Vietnam',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '35 - 58 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior Analyst',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Equity Research', 'Mô hình định giá tài chính', 'Thăm dò thực địa dự án', 'Báo cáo đầu tư song ngữ'],
    jdSummary: [
      'Nghiên cứu chuyên sâu ngành bất động sản và bán lẻ tiêu dùng phục vụ quyết định giải ngân quỹ.',
      'Gặp gỡ ban lãnh đạo các doanh nghiệp niêm yết và khảo sát tiến độ thực địa dự án.',
      'Xây dựng mô hình dự báo doanh thu, lợi nhuận và định giá cổ phiếu độc lập.'
    ],
    perks: ['Làm việc tại quỹ quản lý tài sản lớn nhất Việt Nam', 'Thưởng hiệu quả đầu tư năm hấp dẫn'],
    aiMatch: 95
  },
  {
    id: 413,
    title: 'Chuyên Viên Cao Cấp Tái Cấu Trúc Tài Chính & M&A',
    company: 'Ngân hàng TMCP Tiên Phong (TPBank)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '32 - 50 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 92, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Tái cấu trúc nợ', 'Tư vấn M&A', 'Định giá tài sản bảo đảm', 'Pháp lý tài chính'],
    jdSummary: [
      'Tư vấn các giải pháp tái cấu trúc nguồn vốn và sáp nhập doanh nghiệp cho khách hàng lớn.',
      'Định giá và lập phương án xử lý nợ có tài sản đảm bảo quy mô hàng nghìn tỷ đồng.',
      'Phối hợp với các tổ chức tư vấn luật hoàn thiện cấu trúc giao dịch an toàn.'
    ],
    perks: ['Gói lương thưởng cạnh tranh top ngân hàng số', 'Lộ trình thăng tiến chuyên gia rõ ràng'],
    aiMatch: 91
  },
  {
    id: 414,
    title: 'Investment Associate (Khối Quỹ Đầu Tư Tư Nhân Private Equity)',
    company: 'Tập đoàn Quản lý Quỹ VinaCapital',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '40 - 65 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Investment Associate',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Private Equity', 'Financial Due Diligence', 'LBO Modeling', 'Thương thảo cổ đông'],
    jdSummary: [
      'Thực hiện thẩm định tài chính chi tiết (Financial Due Diligence) các thương vụ đầu tư cổ phần tư nhân.',
      'Xây dựng kịch bản tài chính phức tạp và đánh giá tỷ suất hoàn vốn nội bộ (IRR).',
      'Đồng hành hỗ trợ tái cơ cấu quản trị tại các công ty trong danh mục đầu tư.'
    ],
    perks: ['Thưởng thành công thương vụ (Carried Interest)', 'Môi trường làm việc chuẩn Wall Street'],
    aiMatch: 96
  },
  {
    id: 415,
    title: 'Trưởng Phòng Kế Hoạch & Quản Lý Chi Phí Hoạt Động (Cost Control)',
    company: 'Ngân hàng TMCP Phát triển TP.HCM (HDBank)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Trưởng phòng',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Cost Control', 'Tối ưu hóa CIR', 'Quản trị ngân sách OPEX/CAPEX', 'Kiểm soát mua sắm'],
    jdSummary: [
      'Kiểm soát toàn bộ chi phí hoạt động OPEX và chi phí đầu tư CAPEX của toàn hệ thống ngân hàng.',
      'Tối ưu hóa tỷ lệ chi phí trên thu nhập (CIR) theo chỉ tiêu Hội đồng Quản trị giao.',
      'Thẩm định hiệu quả kinh tế các đề xuất mua sắm trang thiết bị và phần mềm chuyển đổi số.'
    ],
    perks: ['Chế độ phúc lợi ngân hàng hấp dẫn', 'Môi trường năng động nhiều cơ hội phát triển'],
    aiMatch: 90
  },
  {
    id: 416,
    title: 'Chuyên Viên Kiểm Soát Tuân Thủ & Phòng Chống Rửa Tiền (AML/CTF)',
    company: 'Ngân hàng TMCP Hàng Hải Việt Nam (MSB)',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['AML/CTF', 'Kiểm soát tuân thủ', 'Rà soát giao dịch đáng ngờ', 'Cảnh báo rủi ro gian lận'],
    jdSummary: [
      'Giám sát và phân tích các giao dịch có dấu hiệu đáng ngờ theo Luật Phòng chống rửa tiền.',
      'Phối hợp với Cục Phòng chống rửa tiền thuộc NHNN cung cấp thông tin điều tra.',
      'Cập nhật chính sách tuân thủ nội bộ và tổ chức đào tạo cho cán bộ nghiệp vụ.'
    ],
    perks: ['Công việc ổn định, phúc lợi đầy đủ', 'Được tài trợ học chứng chỉ quốc tế CAMS'],
    aiMatch: 88
  },
  {
    id: 417,
    title: 'Chuyên Viên Định Phí Bảo Hiểm (Actuary Specialist)',
    company: 'Tổng Công ty Bảo hiểm Bảo Việt (Bảo Việt Nhân Thọ)',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '30 - 52 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Actuary Specialist',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 10, evaluated14d: 9, responseRate: 90, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Actuarial Science', 'Định phí sản phẩm bảo hiểm', 'Dự phòng rủi ro IFRS 17', 'Mô hình Prophet'],
    jdSummary: [
      'Thiết kế và tính toán phí bảo hiểm cho các sản phẩm bảo hiểm nhân thọ và liên kết đầu tư.',
      'Xây dựng mô hình trích lập dự phòng kỹ thuật đáp ứng chuẩn mực báo cáo tài chính quốc tế IFRS 17.',
      'Đánh giá khả năng thanh toán và rủi ro tài chính định kỳ hàng quý.'
    ],
    perks: ['Hỗ trợ lệ phí thi và ngày nghỉ học thi các chứng chỉ SOA/IFoA', 'Lương thưởng hấp dẫn'],
    aiMatch: 94
  },
  {
    id: 418,
    title: 'Quản Lý Khách Hàng Doanh Nghiệp Lớn (Corporate Banking Lead)',
    company: 'Ngân hàng TMCP Lộc Phát Việt Nam (LPBank)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Corporate Banking', 'Tín dụng doanh nghiệp lớn', 'Huy động vốn', 'Quan hệ khách hàng'],
    jdSummary: [
      'Khai thác và chăm sóc các tập đoàn xây dựng, năng lượng và sản xuất kinh doanh quy mô lớn.',
      'Tư vấn các gói tài trợ vốn lưu động, phát hành bảo lãnh dự thầu và quản lý dòng tiền.',
      'Dẫn dắt nhóm quan hệ khách hàng doanh nghiệp hoàn thành chỉ tiêu tăng trưởng tín dụng.'
    ],
    perks: ['Gói thu nhập hấp dẫn theo kết quả kinh doanh', 'Chính sách thăng tiến minh bạch'],
    aiMatch: 92
  },
  {
    id: 419,
    title: 'Senior Financial Analyst (Khối Khách Hàng Doanh Nghiệp Hàn Quốc)',
    company: 'Công ty Chứng khoán Mirae Asset Việt Nam',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior Analyst',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 92, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['Financial Analysis', 'Tiếng Hàn/Anh lưu loát', 'Tư vấn niêm yết IB', 'Thương vụ M&A'],
    jdSummary: [
      'Hỗ trợ các doanh nghiệp Hàn Quốc tại Việt Nam tiếp cận nguồn vốn qua kênh phát hành trái phiếu và cổ phiếu.',
      'Phân tích năng lực tài chính và lập hồ sơ chào bán chứng khoán riêng lẻ.',
      'Soạn thảo các tài liệu thuyết trình thương vụ chuyên nghiệp bằng tiếng Hàn hoặc tiếng Anh.'
    ],
    perks: ['Môi trường làm việc tập đoàn tài chính số 1 Hàn Quốc', 'Cơ hội onsite tại Seoul'],
    aiMatch: 91
  },
  {
    id: 420,
    title: 'Quản Lý Đối Soát Tài Chính & Thanh Toán Trung Gian',
    company: 'Công ty Cổ phần Dịch vụ Di động Trực tuyến (MoMo)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 17, evaluated14d: 16, responseRate: 94, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['Reconciliation', 'FinTech Settlement', 'Quy trình đối soát ngân hàng', 'SQL nâng cao'],
    jdSummary: [
      'Quản lý hệ thống đối soát dữ liệu giao dịch tự động giữa ví điện tử MoMo và hơn 40 ngân hàng.',
      'Xử lý nhanh chóng các giao dịch chênh lệch, khiếu nại hoàn tiền và phòng ngừa thất thoát.',
      'Tự động hóa báo cáo dòng tiền và thời gian thanh toán công nợ cho các đối tác bán hàng.'
    ],
    perks: ['Thưởng cổ phiếu ESOP thường niên', 'Môi trường làm việc năng động và nhiều thử thách công nghệ'],
    aiMatch: 93
  },
  {
    id: 421,
    title: 'Trưởng Nhóm Phát Triển Sản Phẩm Tài Chính Số (WealthTech Product Owner)',
    company: 'Công ty Cổ phần Chứng khoán VNDIRECT',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '30 - 50 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Product Owner',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['Product Owner', 'Chứng chỉ quỹ Dwealth', 'Thiết kế hành trình đầu tư', 'Agile/Scrum'],
    jdSummary: [
      'Chịu trách nhiệm thiết kế các sản phẩm tiết kiệm sinh lời, chứng chỉ quỹ và tích lũy mục tiêu trên App DGo.',
      'Phối hợp với IT và UI/UX Designer xây dựng giao diện đầu tư đơn giản, trực quan cho nhà đầu tư F0.',
      'Theo dõi các chỉ số đo lường hiệu quả sản phẩm (MAU, Volume giao dịch, Retention).'
    ],
    perks: ['Chế độ đãi ngộ cạnh tranh bậc nhất ngành chứng khoán', 'Văn hóa tôn trọng sáng tạo cá nhân'],
    aiMatch: 92
  },
  {
    id: 422,
    title: 'Chuyên Viên Xử Lý Nợ & Tái Thiết Danh Mục Khách Hàng',
    company: 'Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '20 - 35 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM & Cần Thơ',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['Xử lý nợ xấu NPL', 'Thẩm định phát mãi tài sản', 'Đàm phán cơ cấu nợ', 'Pháp lý tố tụng'],
    jdSummary: [
      'Trực tiếp đàm phán với khách hàng có nợ quá hạn để thống nhất phương án cơ cấu lại lịch trả nợ.',
      'Thực hiện thủ tục bán đấu giá tài sản bảo đảm thu hồi vốn theo đúng quy định pháp luật.',
      'Quản lý hồ sơ pháp lý và phối hợp với cơ quan thi hành án dân sự.'
    ],
    perks: ['Thưởng nóng theo tỷ lệ thu hồi nợ thành công', 'Chế độ phúc lợi Sacombank đầy đủ'],
    aiMatch: 87
  },
  {
    id: 423,
    title: 'Senior Audit Associate (Khối Kiểm Toán Ngân Hàng & FinTech)',
    company: 'PwC Vietnam (PricewaterhouseCoopers)',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '26 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM & Hà Nội',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Senior Associate',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '8 giờ trước',
    verified: true,
    skills: ['External Audit', 'Big 4 Experience', 'Kiểm toán ngân hàng', 'IFRS Standards', 'ACCA/CPA'],
    jdSummary: [
      'Trưởng nhóm phụ trách kiểm toán báo cáo tài chính cho các ngân hàng thương mại và ví điện tử lớn.',
      'Đánh giá tính tuân thủ các chuẩn mực kế toán IFRS 9 về trích lập dự phòng rủi ro tín dụng.',
      'Soạn thảo thư quản lý (Management Letter) chỉ ra các điểm yếu kiểm soát nội bộ.'
    ],
    perks: ['Môi trường làm việc Big 4 chuẩn mực quốc tế', 'Chính sách tài trợ học bổng ACCA/CPA'],
    aiMatch: 95
  },
  {
    id: 424,
    title: 'M&A Due Diligence Consultant (Tư Vấn Tài Chính Doanh Nghiệp)',
    company: 'KPMG Vietnam',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'finance',
    salaryBadge: '30 - 48 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Consultant / Senior',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '8 giờ trước',
    verified: true,
    skills: ['Financial Due Diligence', 'Tư vấn M&A', 'Chất lượng lợi nhuận (QoE)', 'Vốn lưu động ròng (NWC)'],
    jdSummary: [
      'Thực hiện thẩm định chất lượng lợi nhuận (Quality of Earnings) và nợ ròng cho các thương vụ M&A.',
      'Xác định các yếu tố rủi ro tài chính tiềm ẩn có thể ảnh hưởng đến mức định giá mua bán doanh nghiệp.',
      'Hỗ trợ khách hàng trong quá trình đàm phán hợp đồng mua bán cổ phần (SPA).'
    ],
    perks: ['Làm việc cùng các chuyên gia hàng đầu khu vực châu Á - Thái Bình Dương', 'Gói bảo hiểm toàn diện'],
    aiMatch: 94
  }
];

console.log('Finance jobs generated:', financeJobs.length);
