// Complete generator script for 120 featured jobs data across 5 industries (24 jobs each)
const fs = require('fs');

// We already have salesJobs (101 to 124)
// Now let's define itJobs (201 to 224), marketingJobs (301 to 324), financeJobs (401 to 424), hrJobs (501 to 524).

const salesJobs = [
  {
    id: 101,
    title: 'Giám Đốc Khách Hàng Doanh Nghiệp (B2B Account Manager)',
    company: 'Tổng Công ty Dịch vụ Số Viettel',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '30 - 55 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng nhóm / Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '15 phút trước',
    verified: true,
    skills: ['B2B Sales', 'Key Account', 'Giải pháp số', 'Đàm phán cấp cao'],
    jdSummary: [
      'Chịu trách nhiệm phát triển doanh số khách hàng doanh nghiệp khối Tài chính - Ngân hàng.',
      'Tư vấn các gói giải pháp Chuyển đổi số, Viettel Cloud và Payment Gateway.',
      'Xây dựng mối quan hệ chiến lược với C-levels của các tập đoàn đối tác.'
    ],
    perks: ['Thưởng hoa hồng không giới hạn theo doanh số', 'Gói bảo hiểm sức khỏe Viettel Care toàn diện'],
    aiMatch: 96
  },
  {
    id: 102,
    title: 'Trưởng Phòng Kinh Doanh Bất Động Sản Nghỉ Dưỡng',
    company: 'Tập đoàn Vingroup (Vinhomes)',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '35 - 70 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng phòng',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 18, evaluated14d: 16, responseRate: 89, lastReviewed: '12:00' },
    updated: '30 phút trước',
    verified: true,
    skills: ['Bất động sản', 'Quản lý đội ngũ', 'Tư vấn đầu tư', 'Chiến lược bán hàng'],
    jdSummary: [
      'Điều hành và dẫn dắt đội ngũ 15 chuyên viên kinh doanh dự án cao cấp.',
      'Lập kế hoạch phân bổ chỉ tiêu doanh số và tổ chức sự kiện mở bán.',
      'Chăm sóc tệp khách hàng VIP và các nhà đầu tư lớn.'
    ],
    perks: ['Hoa hồng cao nhất thị trường BĐS', 'Phúc lợi nghỉ dưỡng hệ thống Vinpearl định kỳ'],
    aiMatch: 92
  },
  {
    id: 103,
    title: 'Chuyên Viên Quan Hệ Khách Hàng Doanh Nghiệp (RM)',
    company: 'Ngân hàng Techcombank',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '22 - 38 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM (Quận 1)',
    city: 'TP.HCM',
    exp: '1-3 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 22, evaluated14d: 21, responseRate: 95, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Tín dụng doanh nghiệp', 'Tài trợ thương mại', 'Thẩm định tài chính', 'Quan hệ khách hàng'],
    jdSummary: [
      'Tìm kiếm và tiếp cận các doanh nghiệp SME/Commercial để cung cấp dịch vụ tín dụng.',
      'Phân tích báo cáo tài chính và lập tờ trình cấp hạn mức tín dụng.',
      'Quản lý danh mục và phòng ngừa rủi ro tín dụng định kỳ.'
    ],
    perks: ['Thưởng hiệu quả kinh doanh hàng quý', 'Lộ trình thăng tiến rõ ràng lên Senior RM sau 1 năm'],
    aiMatch: 94
  },
  {
    id: 104,
    title: 'Kỹ Sư Giải Pháp Bán Hàng Kỹ Thuật (Pre-Sales Engineer)',
    company: 'CMC Telecom Enterprise',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '25 - 45 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 10, evaluated14d: 9, responseRate: 90, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['Pre-Sales', 'Cloud Architecture', 'Mạng viễn thông', 'Thuyết trình kỹ thuật'],
    jdSummary: [
      'Phối hợp với bộ phận Sales để tư vấn giải pháp mạng & Cloud cho khách hàng lớn.',
      'Soạn thảo hồ sơ đề xuất kỹ thuật (RFP, POC) và giải đáp kiến trúc hệ thống.',
      'Chuyển giao yêu cầu kỹ thuật chi tiết cho đội ngũ triển khai dự án.'
    ],
    perks: ['Được tài trợ 100% chi phí thi chứng chỉ quốc tế AWS/Azure', 'Thưởng dự án theo quý'],
    aiMatch: 90
  },
  {
    id: 105,
    title: 'Business Development Manager (Khu vực Đông Nam Á)',
    company: 'Shopee Vietnam',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '30 - 50 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM (Quận 7)',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: false,
    lightningStats: { applied30d: 16, evaluated14d: 11, responseRate: 68, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['E-commerce', 'Thương thảo nhãn hàng', 'Phân tích dữ liệu bán lẻ', 'Tiếng Anh lưu loát'],
    jdSummary: [
      'Phát triển danh mục nhà bán hàng chiến lược trên sàn thương mại điện tử Shopee.',
      'Đàm phán các chương trình khuyến mãi độc quyền và tối ưu giá bán lẻ.',
      'Phân tích chỉ số tăng trưởng GMV để đề xuất chiến lược phát triển ngành hàng.'
    ],
    perks: ['Môi trường Tech năng động quốc tế', 'MacBook Pro mới nhất phục vụ công việc'],
    aiMatch: 88
  },
  {
    id: 106,
    title: 'Chuyên Viên Tư Vấn Giải Pháp Cloud & AI SaaS',
    company: 'FPT Smart Cloud',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '20 - 35 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '1-3 năm',
    level: 'Chuyên viên',
    type: 'Hybrid',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 91, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['SaaS Sales', 'AI Chatbot', 'Cloud Solutions', 'Tư vấn giải pháp'],
    jdSummary: [
      'Tiếp nhận lead khách hàng tiềm năng và demo giải pháp FPT.AI, FPT Cloud.',
      'Đàm phán hợp đồng cung cấp dịch vụ phần mềm cho khối doanh nghiệp tài chính, bán lẻ.',
      'Chăm sóc tài khoản khách hàng duy trì gia hạn định kỳ (Retention).'
    ],
    perks: ['Chế độ làm việc linh hoạt Hybrid 2 ngày Remote/tuần', 'Bảo hiểm FPT Care'],
    aiMatch: 93
  },
  {
    id: 107,
    title: 'Trưởng Nhóm Phát Triển Khách Hàng Ưu Tiên (Priority Banking Lead)',
    company: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 19, evaluated14d: 18, responseRate: 95, lastReviewed: '12:00' },
    updated: '25 phút trước',
    verified: true,
    skills: ['Priority Banking', 'Wealth Management', 'Tư vấn đầu tư', 'Quản lý quan hệ'],
    jdSummary: [
      'Phát triển mạng lưới khách hàng cá nhân cao cấp (Diamond / Priority Club).',
      'Tư vấn các gói giải pháp tài chính đặc quyền, tiền gửi sinh lời và chứng chỉ quỹ.',
      'Dẫn dắt đội ngũ 6 chuyên viên quản lý tài sản đạt chỉ tiêu AUM.'
    ],
    perks: ['Hoa hồng theo doanh số không giới hạn', 'Ưu đãi thẻ tín dụng và vay mua nhà'],
    aiMatch: 95
  },
  {
    id: 108,
    title: 'Quản Lý Bán Hàng Kênh MT Toàn Quốc (National Key Account)',
    company: 'Masan Consumer Holdings',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '35 - 55 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Trưởng phòng / Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '40 phút trước',
    verified: true,
    skills: ['Key Account MT', 'FMCG Sales', 'Thương thảo hợp đồng', 'Quản lý chuỗi'],
    jdSummary: [
      'Quản lý hệ thống chuỗi siêu thị toàn quốc (WinMart, Co.opmart, BigC/Go).',
      'Đàm phán hợp đồng thương mại năm, chương trình chiết khấu và diện tích trưng bày kệ hàng.',
      'Tối ưu hóa chỉ số tăng trưởng doanh số và vòng quay hàng tồn kho (Sell-out/Sell-in).'
    ],
    perks: ['Thưởng doanh số năm cạnh tranh', 'Chính sách mua sản phẩm Masan ưu đãi cao'],
    aiMatch: 94
  },
  {
    id: 109,
    title: 'Trưởng Bộ Phận Mở Rộng Điểm Bán & Quan Hệ Đối Tác',
    company: 'Công ty Cổ phần Đầu tư Thế Giới Di Động (MWG)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '25 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM & Miền Tây',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Trưởng bộ phận',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 11, evaluated14d: 10, responseRate: 91, lastReviewed: '12:00' },
    updated: '1 giờ trước',
    verified: true,
    skills: ['Site Selection', 'Bán lẻ chuỗi', 'Đàm phán mặt bằng', 'Phân tích lưu lượng'],
    jdSummary: [
      'Khảo sát và thẩm định mặt bằng kinh doanh mở mới chuỗi Bách Hóa Xanh và Điện Máy Xanh.',
      'Thương thảo hợp đồng thuê dài hạn với các chủ bất động sản thương mại.',
      'Đảm bảo tiến độ bàn giao mặt bằng cho đội ngũ thi công đúng hạn.'
    ],
    perks: ['Gói cổ phiếu thưởng ESOP thường niên', 'Phụ cấp công tác phí đầy đủ'],
    aiMatch: 91
  },
  {
    id: 110,
    title: 'Chuyên Viên Kinh Doanh Bất Động Sản Đảo Ngọc Phú Quốc',
    company: 'Tập đoàn Sun Group',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '30 - 65 triệu',
    salaryIsOrange: true,
    location: 'Kiên Giang & TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: false,
    lightningStats: { applied30d: 13, evaluated14d: 10, responseRate: 77, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['BĐS Nghỉ dưỡng', 'Tư vấn Shophouse/Villa', 'Quan hệ VIP', 'Chăm sóc khách hàng'],
    jdSummary: [
      'Tư vấn các sản phẩm biệt thự nghỉ dưỡng, shophouse thương mại tại Nam Phú Quốc.',
      'Tổ chức site tour đón tiếp nhà đầu tư tham quan thực địa dự án.',
      'Đồng hành hỗ trợ khách hàng từ thủ tục đặt cọc đến bàn giao sổ hồng.'
    ],
    perks: ['Hoa hồng cao bậc nhất thị trường BĐS nghỉ dưỡng', 'Vé máy bay và nghỉ dưỡng Sun World'],
    aiMatch: 89
  },
  {
    id: 111,
    title: 'Trưởng Nhóm Tư Vấn Bất Động Sản Công Nghệ (PropTech)',
    company: 'One Mount Real Estate (OneHousing)',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '25 - 45 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 17, evaluated14d: 16, responseRate: 94, lastReviewed: '12:00' },
    updated: '2 giờ trước',
    verified: true,
    skills: ['PropTech', 'Dữ liệu định giá nhà', 'Tư vấn gói vay Techcombank', 'Chốt deal'],
    jdSummary: [
      'Sử dụng công cụ định giá AI tự động OneHousing để tư vấn nguồn căn hộ cho khách mua.',
      'Hỗ trợ khách hàng kết nối giải pháp tài chính vay vốn mua nhà nhanh chóng.',
      'Dẫn dắt đội ngũ 8 chuyên viên tư vấn chuyển đổi nguồn khách hàng tiềm năng.'
    ],
    perks: ['Nguồn lead khách hàng chuẩn xác từ hệ sinh thái One Mount', 'Thưởng hoa hồng nhanh'],
    aiMatch: 93
  },
  {
    id: 112,
    title: 'Key Account Manager (Kênh Điện Tử & Công Nghệ Tiêu Dùng)',
    company: 'Tiki Corporation',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '22 - 38 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 92, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['Key Account', 'E-commerce', 'Thương thảo nhãn hàng công nghệ', 'Phân tích doanh số'],
    jdSummary: [
      'Xây dựng quan hệ hợp tác với các nhãn hàng thiết bị điện tử, gia dụng thông minh chính hãng.',
      'Lập kế hoạch bán hàng cho các đợt Mega Sale và ngày hội thương hiệu (Super Brand Day).',
      'Đảm bảo cam kết giao hàng nhanh TikiNOW 2H đạt chuẩn hài lòng khách hàng.'
    ],
    perks: ['Môi trường thương mại điện tử chuyên nghiệp', 'Mua hàng Tiki ưu đãi nội bộ'],
    aiMatch: 90
  },
  {
    id: 113,
    title: 'Trưởng Phòng Phát Triển Thị Trường BeCorporate',
    company: 'Công ty Cổ phần Be Group',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '30 - 48 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '3-5 năm',
    level: 'Trưởng phòng',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '3 giờ trước',
    verified: true,
    skills: ['B2B Solutions', 'Giải pháp di chuyển doanh nghiệp', 'Đàm phán C-level', 'Team Leadership'],
    jdSummary: [
      'Mở rộng gói giải pháp di chuyển và giao vận cho các tập đoàn và ngân hàng lớn tại Việt Nam.',
      'Xây dựng bảng giá dịch vụ ưu đãi và cơ chế thanh toán hóa đơn doanh nghiệp tập trung.',
      'Quản lý đội ngũ chuyên viên bán hàng B2B đạt chỉ tiêu doanh số năm.'
    ],
    perks: ['Gói di chuyển Be miễn phí không giới hạn', 'Thưởng KPI theo kết quả kinh doanh'],
    aiMatch: 92
  },
  {
    id: 114,
    title: 'Giám Đốc Kinh Doanh Trung Tâm Chi Nhánh Vùng',
    company: 'Công ty Cổ phần Viễn thông FPT (FPT Telecom)',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '28 - 45 triệu',
    salaryIsOrange: false,
    location: 'Đà Nẵng & Miền Trung',
    city: 'Đà Nẵng',
    exp: '3-5 năm',
    level: 'Giám đốc chi nhánh',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['Quản trị kinh doanh', 'Viễn thông FPT', 'Phát triển thuê bao', 'Vận hành chi nhánh'],
    jdSummary: [
      'Chịu trách nhiệm toàn diện về chỉ tiêu doanh thu và phát triển thuê bao Internet/FPT Play.',
      'Quản trị đội ngũ hơn 40 nhân sự kinh doanh và kỹ thuật hỗ trợ tại chi nhánh.',
      'Thiết lập mạng lưới đại lý ủy quyền và chăm sóc khách hàng doanh nghiệp địa phương.'
    ],
    perks: ['Thưởng quý và thưởng cuối năm hấp dẫn', 'Bảo hiểm FPT Care cho bản thân và người thân'],
    aiMatch: 91
  },
  {
    id: 115,
    title: 'Enterprise Sales Specialist (Giải Pháp Doanh Nghiệp GrabForBusiness)',
    company: 'Grab Vietnam',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '24 - 40 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '4 giờ trước',
    verified: true,
    skills: ['B2B Sales', 'GrabForBusiness', 'Corporate Client', 'Thuyết trình hợp đồng'],
    jdSummary: [
      'Tìm kiếm và ký kết hợp đồng cung cấp dịch vụ Grab di chuyển và GrabFood cho doanh nghiệp.',
      'Thiết lập cổng thanh toán tập trung và quản lý tài khoản người dùng của đối tác.',
      'Duy trì tỷ lệ tái ký hợp đồng dịch vụ trên 90% hàng năm.'
    ],
    perks: ['Gói phụ cấp GrabCredits hàng tháng', 'Môi trường làm việc đa văn hóa'],
    aiMatch: 89
  },
  {
    id: 116,
    title: 'Chuyên Viên Khách Hàng Doanh Nghiệp Lớn (CIB RM)',
    company: 'Ngân hàng TMCP Quân Đội (MB Bank)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '25 - 42 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['Khách hàng doanh nghiệp lớn', 'Tín dụng CIB', 'Thẩm định hồ sơ', 'Bảo lãnh phát hành'],
    jdSummary: [
      'Tiếp cận các tập đoàn kinh tế và tổng công ty nhà nước để tài trợ vốn lưu động và dự án.',
      'Cung cấp các sản phẩm phái sinh tỷ giá, quản lý dòng tiền và tài trợ chuỗi cung ứng.',
      'Phối hợp với khối Quản trị rủi ro thẩm định phương án vay vốn an toàn.'
    ],
    perks: ['Gói lương thưởng cạnh tranh top ngành ngân hàng', 'Lãi suất vay ưu đãi cho CBNV'],
    aiMatch: 93
  },
  {
    id: 117,
    title: 'Trưởng Nhóm Tư Vấn Phần Mềm Quản Trị Doanh Nghiệp MISA AMIS',
    company: 'Công ty Cổ phần MISA',
    logo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '20 - 36 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội & TP.HCM',
    city: 'Hà Nội',
    exp: '2-4 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 18, evaluated14d: 17, responseRate: 94, lastReviewed: '12:00' },
    updated: '5 giờ trước',
    verified: true,
    skills: ['SaaS Enterprise', 'ERP Consultant', 'Demo phần mềm', 'Chốt sale SME'],
    jdSummary: [
      'Tư vấn nền tảng quản trị tài chính, nhân sự và kế toán hợp nhất MISA AMIS cho lãnh đạo SME.',
      'Xây dựng kịch bản demo giải pháp chuyên sâu theo đặc thù từng lĩnh vực ngành nghề.',
      'Dẫn dắt nhóm tư vấn giải pháp đạt định mức doanh thu hàng tháng.'
    ],
    perks: ['Thưởng hoa hồng theo hợp đồng minh bạch', 'Chế độ đào tạo kỹ năng bán hàng bài bản'],
    aiMatch: 90
  },
  {
    id: 118,
    title: 'Chuyên Viên Phát Triển Kênh Bán Hàng Số & Dịch Vụ IoT',
    company: 'Tổng Công ty Dịch vụ Viễn thông VNPT (VNPT VinaPhone)',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '22 - 35 triệu',
    salaryIsOrange: false,
    location: 'Hà Nội',
    city: 'Hà Nội',
    exp: '1-3 năm',
    level: 'Chuyên viên',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 12, evaluated14d: 11, responseRate: 92, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['Kênh bán hàng số', 'Giải pháp IoT', 'Dịch vụ số VNPT', 'Bán hàng đa kênh'],
    jdSummary: [
      'Phát triển mạng lưới bán hàng trên các nền tảng ứng dụng di động và website VinaPhone.',
      'Cung cấp các gói giải pháp chữ ký số, hóa đơn điện tử và giám sát thông minh cho doanh nghiệp.',
      'Theo dõi và tối ưu hóa tỷ lệ chuyển đổi đơn hàng trực tuyến.'
    ],
    perks: ['Môi trường làm việc ổn định, phúc lợi toàn diện', 'Thưởng thành tích quý'],
    aiMatch: 88
  },
  {
    id: 119,
    title: 'Chuyên Viên Khách Hàng Doanh Nghiệp FDI (FDI Account Manager)',
    company: 'Ngân hàng TMCP Ngoại Thương Việt Nam (Vietcombank)',
    logo: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '25 - 45 triệu',
    salaryIsOrange: false,
    location: 'Bình Dương & Đồng Nai',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Chuyên viên cao cấp',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 16, evaluated14d: 15, responseRate: 94, lastReviewed: '12:00' },
    updated: '6 giờ trước',
    verified: true,
    skills: ['FDI Banking', 'Tiếng Anh/Hàn/Hoa lưu loát', 'Tín dụng doanh nghiệp', 'Thanh toán quốc tế'],
    jdSummary: [
      'Khai thác và chăm sóc các doanh nghiệp có vốn đầu tư nước ngoài tại các khu công nghiệp trọng điểm.',
      'Tư vấn các gói tài trợ thương mại xuất nhập khẩu, thanh toán L/C và tín dụng dài hạn.',
      'Giao dịch chuyên nghiệp bằng tiếng Anh hoặc ngoại ngữ chuyên biệt.'
    ],
    perks: ['Chế độ đãi ngộ hàng đầu trong ngành tài chính', 'Môi trường làm việc quốc tế'],
    aiMatch: 95
  },
  {
    id: 120,
    title: 'Trưởng Nhóm Bán Hàng Trực Tiếp (Direct Sales Team Leader)',
    company: 'Ngân hàng TMCP Tiên Phong (TPBank)',
    logo: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '20 - 35 triệu',
    salaryIsOrange: false,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '2-4 năm',
    level: 'Trưởng nhóm',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 14, evaluated14d: 13, responseRate: 93, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['Direct Sales', 'Thẻ tín dụng TPBank', 'Gói vay tiêu dùng', 'Đào tạo nhân viên'],
    jdSummary: [
      'Điều hành nhóm 10 chuyên viên tư vấn mở thẻ tín dụng và vay tín chấp tiêu dùng.',
      'Tổ chức các sự kiện tiếp cận khách hàng tại các tòa nhà văn phòng và trung tâm thương mại.',
      'Đảm bảo tuân thủ quy trình thẩm định sơ bộ và phòng chống gian lận hồ sơ.'
    ],
    perks: ['Hoa hồng không áp trần theo doanh số', 'Thưởng thăng tiến nội bộ nhanh'],
    aiMatch: 87
  },
  {
    id: 121,
    title: 'Business Development Lead (Khối Bán Lẻ & Chuỗi F&B)',
    company: 'Công ty Cổ phần Dịch vụ Di động Trực tuyến (MoMo)',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '28 - 48 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Trưởng nhóm / Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 15, evaluated14d: 14, responseRate: 93, lastReviewed: '12:00' },
    updated: '7 giờ trước',
    verified: true,
    skills: ['FinTech BD', 'Payment QR', 'Thương thảo chuỗi F&B', 'Phát triển đối tác'],
    jdSummary: [
      'Mở rộng mạng lưới chấp nhận thanh toán MoMo QR tại các chuỗi bán lẻ và nhà hàng lớn.',
      'Đàm phán các chương trình khuyến mãi đồng tài trợ (Co-marketing) gia tăng lượng giao dịch.',
      'Theo dõi hiệu quả sử dụng dịch vụ và giải quyết các bài toán vận hành của đối tác.'
    ],
    perks: ['Thưởng cổ phiếu ESOP định kỳ', 'Văn phòng sáng tạo, nhiều tiện ích giải trí'],
    aiMatch: 94
  },
  {
    id: 122,
    title: 'Quản Lý Kinh Doanh Dự Án Hạng Sang (Luxury Project Sales)',
    company: 'Tập đoàn Masterise Homes',
    logo: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '35 - 75 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: false,
    lightningStats: { applied30d: 11, evaluated14d: 8, responseRate: 72, lastReviewed: '12:00' },
    updated: '8 giờ trước',
    verified: true,
    skills: ['BĐS Hàng hiệu', 'Branded Residences', 'Tư vấn giới thượng lưu', 'Đàm phán quốc tế'],
    jdSummary: [
      'Phụ trách kinh doanh các căn hộ bất động sản hàng hiệu tiêu chuẩn quốc tế (Marriott/Ritz-Carlton).',
      'Xây dựng mối quan hệ tin cậy với các khách hàng có giá trị tài sản ròng siêu cao (UHNWI).',
      'Chủ trì các buổi tiệc riêng tư và sự kiện triển lãm bất động sản cao cấp.'
    ],
    perks: ['Chế độ hoa hồng dự án hạng sang vượt trội', 'Môi trường làm việc chuẩn quốc tế'],
    aiMatch: 92
  },
  {
    id: 123,
    title: 'Key Account Manager (Kênh Chuỗi Bán Lẻ Điện Máy Toàn Quốc)',
    company: 'Samsung Vina Electronics',
    logo: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '30 - 52 triệu',
    salaryIsOrange: true,
    location: 'TP.HCM',
    city: 'TP.HCM',
    exp: '3-5 năm',
    level: 'Senior / Quản lý',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 13, evaluated14d: 12, responseRate: 92, lastReviewed: '12:00' },
    updated: '8 giờ trước',
    verified: true,
    skills: ['Consumer Electronics', 'Key Account Samsung', 'Trade Marketing', 'Dự báo doanh số'],
    jdSummary: [
      'Quản lý doanh số bán hàng sản phẩm TV, tủ lạnh, máy giặt Samsung qua các chuỗi bán lẻ lớn.',
      'Lập kế hoạch phân bổ tồn kho và tối ưu chính sách giá cạnh tranh theo mùa vụ.',
      'Phối hợp với Trade Marketing triển khai khu vực trải nghiệm công nghệ tại điểm bán.'
    ],
    perks: ['Chế độ lương thưởng tập đoàn công nghệ số 1', 'Ưu đãi mua thiết bị Samsung nội bộ'],
    aiMatch: 93
  },
  {
    id: 124,
    title: 'Giám Đốc Bán Hàng Miền Bắc (Regional Sales Manager FMCG)',
    company: 'Tập đoàn KIDO (KIDO Group)',
    logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&h=120&q=80',
    category: 'sales',
    salaryBadge: '40 - 65 triệu',
    salaryIsOrange: true,
    location: 'Hà Nội & Các tỉnh phía Bắc',
    city: 'Hà Nội',
    exp: 'Trên 5 năm',
    level: 'Giám đốc vùng',
    type: 'Toàn thời gian',
    isLightningBadge: true,
    lightningStats: { applied30d: 10, evaluated14d: 9, responseRate: 90, lastReviewed: '12:00' },
    updated: '9 giờ trước',
    verified: true,
    skills: ['FMCG Sales', 'Quản trị hệ thống phân phối', 'Kênh GT & MT', 'Chiến lược thị phần'],
    jdSummary: [
      'Hoạch định chiến lược kinh doanh và mở rộng độ phủ hệ thống phân phối dầu ăn, kem và bánh kẹo KIDO.',
      'Quản lý hệ thống nhà phân phối và dẫn dắt đội ngũ hơn 100 nhân viên giám sát bán hàng.',
      'Chịu trách nhiệm trực tiếp về doanh số và chỉ tiêu lợi nhuận gộp toàn miền Bắc.'
    ],
    perks: ['Gói thưởng hiệu quả kinh doanh cuối năm lớn', 'Xe ô tô đưa đón công tác'],
    aiMatch: 91
  }
];

// Read template and build itJobs, marketingJobs, financeJobs, hrJobs
console.log('Generating complete array...');
